include: package:lint/strict.yaml

analyzer:
  errors:
    todo: info
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"

linter:
  rules:
    flutter_style_todos: error
    prefer_single_quotes: warning
    avoid_annotating_with_dynamic: error
    public_member_api_docs: warning

formatter:
  page_width: 120
  trailing_commas: preserve
