name: dpip
description: "Disaster Prevention Information Platform"
publish_to: 'none'
version: 3.2.1+1

environment:
  sdk: ^3.12.2

dependencies:
  dio: ^5.10.0
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  go_router: ^17.3.0
  intl: ^0.20.2
  json_annotation: ^4.12.0
  maplibre_gl: ^0.25.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  talker_flutter: ^5.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  freezed: ^3.1.0
  json_serializable: ^6.14.0

flutter:
  uses-material-design: true
  generate: true
  shaders:
    - shaders/fog.frag
    - shaders/thunderstorm.frag
    - shaders/weather_sky.frag
  assets:
    - assets/translations/
    - assets/map/
    - assets/wallpaper/day/
    - assets/wallpaper/dusk/
    - assets/wallpaper/night/
    - assets/DPIP.png
    - assets/ExpTech.png
    - assets/box.json
    - assets/location.json.gz
    - assets/notify_test.json
    - assets/time.json.gz
