#!/usr/bin/env bash
# The test suite, with line coverage for lib/.
#
#     tool/dev/coverage.sh                # always runs
#     tool/dev/coverage.sh --if-changed   # skips when nothing it reads changed
#
# It writes `coverage/lcov.info` — what CI uploads to Codecov, what the editor
# reads, and what genhtml turns into `coverage/html/` wherever lcov is installed
# (`brew install lcov`). Both are gitignored.
#
# Generated code is not in it: `flutter test` leaves out every file marked
# `// coverage:ignore-file`, which build.yaml and l10n.yaml put into everything
# the generators write.
#
# This *is* the test suite, not a run beside it: CI's test step is this script,
# and so is tool/check.sh's. A failing test fails here exactly as it does in
# tool/dev/test.sh.
#
# `--if-changed` is what tool/check.sh uses: the answer depends only on the
# files the suite reads, so an unchanged tree keeps the report it already has
# and costs a hash instead of a minute.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
cd "$(repo_root)"

if_changed=''
case "${1:-}" in
'') ;;
--if-changed) if_changed=1 ;;
*)
  printf 'usage: tool/dev/coverage.sh [--if-changed]\n' >&2
  exit 2
  ;;
esac

readonly out=coverage
readonly work=.dart_tool/dpip_coverage
mkdir -p "$out" "$work"

# Every library in lib/, as the test runner sees them.
#
# Generated files are imported like the rest; their `// coverage:ignore-file` is
# what keeps them out of the numbers. `part of` files cannot be imported on
# their own and are reached through their library anyway.
libraries() {
  git ls-files -co --exclude-standard -z -- 'lib/*.dart' |
    xargs -0 grep -L '^part of' -- || true
}

# Every step checks its own status. This runs as `cached`'s command, which calls
# it on the left of a `||` — and bash switches `set -e` off for everything
# executed there, functions included. Without the explicit returns a failing
# suite would fall through, the function would end on a status of 0, and the
# cache would record a pass for a tree whose tests fail.
run_coverage() {
  # A library no test imports is not in the VM's coverage at all — not at 0%,
  # absent — so a total built from the suite alone leaves it out and reads
  # higher than the truth. When this was written, 85 of 489 hand-written files
  # were missing that way, bootstrap.dart among them. One generated test that
  # imports everything puts every executable line on the books, and running it
  # beside the suite costs a few seconds of compile, not a second test run.
  #
  # Under .dart_tool rather than test/: it is regenerated on every run, belongs
  # to no one, and nothing that walks test/ should ever find it.
  local all="$work/all_libraries_test.dart"
  {
    printf '// Generated by tool/dev/coverage.sh on every run. Not committed.\n'
    printf "import 'package:flutter_test/flutter_test.dart';\n"
    local i=0 file
    while IFS= read -r file; do
      printf "import 'package:dpip/%s' as l%d;\n" "${file#lib/}" "$i"
      i=$((i + 1))
    done < <(libraries)
    printf "\nvoid main() => test('every library is loaded', () {});\n"
  } >"$all" || return

  # `--coverage` writes coverage/lcov.info, and covers this package alone: the
  # default for `--coverage-package` is the current package's name.
  pinned flutter test --coverage test "$all" || return

  # The browsable report, where lcov is installed — one `brew install lcov`
  # away, and CI does not need it because Codecov renders the same numbers. A
  # missing or failing genhtml costs the pages and nothing else.
  if command -v genhtml >/dev/null 2>&1; then
    rm -rf "$out/html"
    genhtml --quiet --output-directory "$out/html" "$out/lcov.info" >/dev/null ||
      printf 'coverage: genhtml failed; the html report was skipped\n' >&2
  fi
}

key="$(cache_key "${TEST_INPUTS[@]}")"
if [[ -n $if_changed && -f $out/lcov.info ]]; then
  cached coverage "$key" run_coverage
else
  # Asked for by name, or nothing to show yet: run, and still leave the stamp
  # so the next check over the same tree knows it has nothing to do.
  DPIP_NO_CACHE=1 cached coverage "$key" run_coverage
fi
