import 'package:awesome_notifications/awesome_notifications.dart';
import 'package:flutter/material.dart';

/// The DPIP notification channel + group catalogue.
///
/// Ported from the legacy app: 21 alert channels across 5 groups (EEW,
/// earthquake, weather, tsunami, other) — each with its own importance, critical-
/// alert flag, sound (`resource://raw/<name>` — Android `.mp3` / iOS `.aiff`),
/// and vibration — plus a standalone `background` service channel. Android caches
/// a channel's settings after first creation, so [version] is bumped whenever a
/// definition changes to force a re-create on next launch. (Adding a brand-new
/// channel needs no bump — `initialize` creates it without touching the others.)
abstract final class NotificationChannels {
  const NotificationChannels._();

  /// Bump when any channel definition below changes, to force a re-create.
  ///
  /// **The bump is not optional paperwork.** Android resolves
  /// `resource://raw/<name>` to a numeric resource ID when a channel is first
  /// created and caches that number system-side; the docs forbid changing a
  /// created channel's behaviour, so the only repair is delete + re-create.
  /// Resource IDs are re-assigned whenever the resource set changes — and when
  /// the sound files were re-encoded in place (#525) with no bump, upgraded
  /// installs kept channels pointing at numbers from an older APK: crossed or
  /// silent sounds on every device that had seen the previous build. Bumping
  /// this counter is what makes [NotificationService] force-update them.
  static const int version = 4;

  /// Default status-bar icon (Android) — a monochrome drawable.
  static const String icon = 'resource://drawable/ic_stat_name';

  /// The channel groups shown in the OS notification settings.
  static final List<NotificationChannelGroup> groups = [
    NotificationChannelGroup(
      channelGroupKey: 'group_eew',
      channelGroupName: '地震速報',
    ),
    NotificationChannelGroup(
      channelGroupKey: 'group_eq',
      channelGroupName: '地震',
    ),
    NotificationChannelGroup(
      channelGroupKey: 'group_info',
      channelGroupName: '天氣',
    ),
    NotificationChannelGroup(
      channelGroupKey: 'group_tsunami',
      channelGroupName: '海嘯',
    ),
    NotificationChannelGroup(
      channelGroupKey: 'group_mesh',
      channelGroupName: 'LoRa 網狀網路',
    ),
    NotificationChannelGroup(
      channelGroupKey: 'group_other',
      channelGroupName: '其他',
    ),
  ];

  /// Every alert channel, in display order.
  static final List<NotificationChannel> channels = [
    NotificationChannel(
      channelGroupKey: 'group_eew',
      channelKey: 'eew_alert-important-v2',
      channelName: '緊急地震速報(重大)',
      channelDescription: '最大震度 5 弱以上以及所在地(鄉鎮)預估震度 4 以上',
      importance: NotificationImportance.Max,
      defaultPrivacy: NotificationPrivacy.Public,
      criticalAlerts: true,
      playSound: true,
      soundSource: 'resource://raw/eew_alert',
      defaultRingtoneType: DefaultRingtoneType.Alarm,
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: true,
      vibrationPattern: highVibrationPattern,
      locked: true,
    ),
    NotificationChannel(
      channelGroupKey: 'group_eew',
      channelKey: 'eew_alert-general-v2',
      channelName: '緊急地震速報(一般)',
      channelDescription: '最大震度 5 弱以上以及所在地(鄉鎮)預估震度 2 以上',
      importance: NotificationImportance.Max,
      defaultPrivacy: NotificationPrivacy.Public,
      criticalAlerts: true,
      playSound: true,
      soundSource: 'resource://raw/eew',
      defaultRingtoneType: DefaultRingtoneType.Alarm,
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: true,
      vibrationPattern: mediumVibrationPattern,
    ),
    NotificationChannel(
      channelGroupKey: 'group_eew',
      channelKey: 'eew_alert-silent-v2',
      channelName: '緊急地震速報(無聲通知)',
      channelDescription: '最大震度 5 弱以上以及所在地(鄉鎮)預估震度 1 以上',
      importance: NotificationImportance.Low,
      defaultPrivacy: NotificationPrivacy.Public,
      playSound: false,
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: true,
      vibrationPattern: lowVibrationPattern,
    ),
    NotificationChannel(
      channelGroupKey: 'group_eew',
      channelKey: 'eew-important-v2',
      channelName: '地震速報(重大)',
      channelDescription: '所在地(鄉鎮)預估震度 4 以上',
      importance: NotificationImportance.Max,
      defaultPrivacy: NotificationPrivacy.Public,
      criticalAlerts: true,
      playSound: true,
      soundSource: 'resource://raw/eew',
      defaultRingtoneType: DefaultRingtoneType.Alarm,
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: true,
      vibrationPattern: highVibrationPattern,
      locked: true,
    ),
    NotificationChannel(
      channelGroupKey: 'group_eew',
      channelKey: 'eew-general-v2',
      channelName: '地震速報(一般)',
      channelDescription: '所在地(鄉鎮)預估震度 2 以上',
      importance: NotificationImportance.Max,
      defaultPrivacy: NotificationPrivacy.Public,
      criticalAlerts: true,
      playSound: true,
      soundSource: 'resource://raw/eew',
      defaultRingtoneType: DefaultRingtoneType.Alarm,
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: true,
      vibrationPattern: mediumVibrationPattern,
    ),
    NotificationChannel(
      channelGroupKey: 'group_eew',
      channelKey: 'eew-silence-v2',
      channelName: '地震速報 (無聲通知)',
      channelDescription: '所在地(鄉鎮)預估震度 1 以上',
      importance: NotificationImportance.Low,
      defaultPrivacy: NotificationPrivacy.Public,
      playSound: false,
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: true,
      vibrationPattern: lowVibrationPattern,
    ),
    NotificationChannel(
      channelGroupKey: 'group_eq',
      channelKey: 'int_report-general-v2',
      channelName: '震度速報(一般)',
      channelDescription: '所在地(鄉鎮)實測震度 3 以上',
      importance: NotificationImportance.High,
      defaultPrivacy: NotificationPrivacy.Public,
      playSound: true,
      soundSource: 'resource://raw/report',
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: true,
      vibrationPattern: mediumVibrationPattern,
    ),
    NotificationChannel(
      channelGroupKey: 'group_eq',
      channelKey: 'int_report-silence-v2',
      channelName: '震度速報 (無聲通知)',
      channelDescription: '所在地(鄉鎮)實測震度 1 以上',
      importance: NotificationImportance.Low,
      defaultPrivacy: NotificationPrivacy.Public,
      playSound: false,
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: true,
      vibrationPattern: lowVibrationPattern,
    ),
    NotificationChannel(
      channelGroupKey: 'group_eq',
      channelKey: 'eq-v2',
      channelName: '強震監視器(一般)',
      channelDescription: '偵測到晃動',
      importance: NotificationImportance.High,
      defaultPrivacy: NotificationPrivacy.Public,
      playSound: true,
      soundSource: 'resource://raw/eq',
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: true,
      vibrationPattern: mediumVibrationPattern,
    ),
    NotificationChannel(
      channelGroupKey: 'group_eq',
      channelKey: 'report-general-v2',
      channelName: '地震報告(一般)',
      channelDescription: '地震報告所在地震度 3 以上',
      importance: NotificationImportance.Default,
      defaultPrivacy: NotificationPrivacy.Public,
      playSound: true,
      soundSource: 'resource://raw/report',
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: true,
      vibrationPattern: lowVibrationPattern,
    ),
    NotificationChannel(
      channelGroupKey: 'group_eq',
      channelKey: 'report-silence-v2',
      channelName: '地震報告 (無聲通知)',
      channelDescription: '地震報告所在地震度 1 以上',
      groupAlertBehavior: GroupAlertBehavior.Children,
      importance: NotificationImportance.Min,
      defaultPrivacy: NotificationPrivacy.Public,
      playSound: false,
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: false,
    ),
    NotificationChannel(
      channelGroupKey: 'group_info',
      channelKey: 'thunderstorm-important-v2',
      channelName: '山區暴雨(重大)',
      channelDescription: '所在地(鄉鎮)發布山區暴雨時',
      importance: NotificationImportance.Max,
      defaultPrivacy: NotificationPrivacy.Public,
      criticalAlerts: true,
      playSound: true,
      soundSource: 'resource://raw/rain',
      defaultRingtoneType: DefaultRingtoneType.Alarm,
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: true,
      vibrationPattern: highVibrationPattern,
      locked: true,
    ),
    NotificationChannel(
      channelGroupKey: 'group_info',
      channelKey: 'thunderstorm-general-v2',
      channelName: '雷雨即時訊息(一般)',
      channelDescription: '所在地(鄉鎮)發布雷雨即時訊息時',
      importance: NotificationImportance.High,
      defaultPrivacy: NotificationPrivacy.Public,
      playSound: true,
      soundSource: 'resource://raw/rain',
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: true,
      vibrationPattern: mediumVibrationPattern,
    ),
    NotificationChannel(
      channelGroupKey: 'group_info',
      channelKey: 'weather_major-important-v2',
      channelName: '天氣警特報(重大)',
      channelDescription: '所在地(鄉鎮)發布紅色燈號之天氣警特報',
      importance: NotificationImportance.Max,
      defaultPrivacy: NotificationPrivacy.Public,
      criticalAlerts: true,
      playSound: true,
      soundSource: 'resource://raw/weather',
      defaultRingtoneType: DefaultRingtoneType.Alarm,
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: true,
      vibrationPattern: highVibrationPattern,
      locked: true,
    ),
    NotificationChannel(
      channelGroupKey: 'group_info',
      channelKey: 'weather_minor-general-v2',
      channelName: '天氣警特報(一般)',
      channelDescription: '所在地(鄉鎮)發布上述除外燈號之天氣警特報',
      importance: NotificationImportance.Default,
      defaultPrivacy: NotificationPrivacy.Public,
      playSound: true,
      soundSource: 'resource://raw/weather',
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: true,
      vibrationPattern: mediumVibrationPattern,
    ),
    NotificationChannel(
      channelGroupKey: 'group_info',
      channelKey: 'evacuation_major-important-v2',
      channelName: '防災資訊(重大)',
      channelDescription: '所在地(鄉鎮)發布土石流、淹水或堰塞湖防災警訊時',
      importance: NotificationImportance.Max,
      defaultPrivacy: NotificationPrivacy.Public,
      criticalAlerts: true,
      playSound: true,
      soundSource: 'resource://raw/warn',
      defaultRingtoneType: DefaultRingtoneType.Alarm,
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: true,
      vibrationPattern: highVibrationPattern,
      locked: true,
    ),
    NotificationChannel(
      channelGroupKey: 'group_info',
      channelKey: 'evacuation_minor-general-v2',
      channelName: '防災資訊(一般)',
      channelDescription: '所在地(鄉鎮)發布土石流、淹水或堰塞湖防災資訊時',
      importance: NotificationImportance.High,
      defaultPrivacy: NotificationPrivacy.Public,
      playSound: true,
      soundSource: 'resource://raw/normal',
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: true,
      vibrationPattern: mediumVibrationPattern,
    ),
    NotificationChannel(
      channelGroupKey: 'group_tsunami',
      channelKey: 'tsunami-important-v2',
      channelName: '海嘯資訊(重大)',
      channelDescription: '海嘯警報發布時',
      importance: NotificationImportance.Max,
      defaultPrivacy: NotificationPrivacy.Public,
      criticalAlerts: true,
      playSound: true,
      soundSource: 'resource://raw/tsunami',
      defaultRingtoneType: DefaultRingtoneType.Alarm,
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: true,
      vibrationPattern: highVibrationPattern,
      locked: true,
    ),
    NotificationChannel(
      channelGroupKey: 'group_tsunami',
      channelKey: 'tsunami-general-v2',
      channelName: '海嘯資訊(一般)',
      channelDescription: '海嘯消息發布時',
      importance: NotificationImportance.Default,
      defaultPrivacy: NotificationPrivacy.Public,
      playSound: true,
      soundSource: 'resource://raw/normal',
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: true,
      vibrationPattern: lowVibrationPattern,
    ),
    NotificationChannel(
      channelGroupKey: 'group_tsunami',
      channelKey: 'tsunami-silent-v2',
      channelName: '太平洋海嘯消息 (無聲通知)',
      channelDescription: '太平洋海嘯消息發布時',
      groupAlertBehavior: GroupAlertBehavior.Children,
      importance: NotificationImportance.Min,
      defaultPrivacy: NotificationPrivacy.Public,
      playSound: false,
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: false,
    ),
    NotificationChannel(
      channelGroupKey: 'group_other',
      channelKey: 'announcement-general-v2',
      channelName: '其他通知',
      channelDescription: '發送公告時',
      importance: NotificationImportance.Default,
      defaultPrivacy: NotificationPrivacy.Public,
      playSound: true,
      soundSource: 'resource://raw/info',
      defaultColor: Colors.red,
      ledColor: Colors.red,
      enableVibration: true,
      vibrationPattern: lowVibrationPattern,
    ),
    // Locally raised, never pushed: the mesh is an off-grid path, so these two
    // are posted by the app itself from the BLE link (see `MeshAlerts`) — there
    // is no server involved and no internet needed for them to arrive.
    NotificationChannel(
      channelGroupKey: 'group_mesh',
      channelKey: 'mesh_message',
      channelName: 'Meshtastic 訊息',
      channelDescription: '從 LoRa 網狀網路收到的訊息',
      importance: NotificationImportance.High,
      defaultColor: const Color(0xFF4CAF50),
      ledColor: const Color(0xFF4CAF50),
      playSound: true,
      vibrationPattern: lowVibrationPattern,
    ),
    NotificationChannel(
      channelGroupKey: 'group_mesh',
      channelKey: 'mesh_node',
      channelName: 'Meshtastic 新節點',
      channelDescription: '第一次聽到某個節點時通知',
      importance: NotificationImportance.Low,
      defaultColor: const Color(0xFF4CAF50),
      channelShowBadge: false,
      playSound: false,
      enableVibration: false,
      enableLights: false,
    ),
    // Standalone (no group): a low-importance, silent channel for any background
    // service notice. Kept for parity with the legacy catalogue; the rewrite's
    // background location is geofence-based (no persistent notification), so it
    // isn't actively posted to today.
    NotificationChannel(
      channelKey: 'background',
      channelName: '自動定位',
      channelDescription: '背景定位服務通知',
      importance: NotificationImportance.Low,
      defaultColor: const Color(0xFF2196F3),
      channelShowBadge: false,
      enableVibration: false,
      enableLights: false,
      playSound: false,
      locked: true,
    ),
  ];

  /// The group a [channelKey] belongs to (`group_eew`, `group_eq`, …), or null
  /// if the key isn't a known channel. Lets the tap router resolve a screen by
  /// group so a new channel routes correctly without touching the mapping.
  static String? groupOf(String channelKey) {
    for (final channel in channels) {
      if (channel.channelKey == channelKey) return channel.channelGroupKey;
    }
    return null;
  }
}
