import 'dart:async';

import 'package:flutter/material.dart';

import 'package:awesome_notifications/awesome_notifications.dart';

Future<void> notifyInit() async {
  await AwesomeNotifications().initialize(
    'resource://drawable/ic_stat_name',
    [
      NotificationChannel(
        channelGroupKey: 'group_eew-v2',
        channelKey: 'eew_alert-important-v2',
        channelName: '緊急地震速報(重大)',
        channelDescription: '最大震度 5 弱以上以及所在地(鄉鎮)預估震度 4 以上',
        importance: NotificationImportance.Max,
        defaultPrivacy: NotificationPrivacy.Public,
        criticalAlerts: true,
        playSound: true,
        soundSource: 'resource://raw/eew_alert',
        defaultRingtoneType: DefaultRingtoneType.Alarm,
        defaultColor: Colors.red,
        ledColor: Colors.red,
        enableVibration: true,
        vibrationPattern: highVibrationPattern,
        locked: true,
      ),
      NotificationChannel(
        channelGroupKey: 'group_eew-v2',
        channelKey: 'eew_alert-general-v2',
        channelName: '緊急地震速報(一般)',
        channelDescription: '最大震度 5 弱以上以及所在地(鄉鎮)預估震度 2 以上',
        importance: NotificationImportance.Max,
        defaultPrivacy: NotificationPrivacy.Public,
        criticalAlerts: true,
        playSound: true,
        soundSource: 'resource://raw/eew',
        defaultRingtoneType: DefaultRingtoneType.Alarm,
        defaultColor: Colors.red,
        ledColor: Colors.red,
        enableVibration: true,
        vibrationPattern: mediumVibrationPattern,
      ),
      NotificationChannel(
        channelGroupKey: 'group_eew-v2',
        channelKey: 'eew_alert-silent-v2',
        channelName: '緊急地震速報(無聲通知)',
        channelDescription: '最大震度 5 弱以上以及所在地(鄉鎮)預估震度 1 以上',
        importance: NotificationImportance.Low,
        defaultPrivacy: NotificationPrivacy.Public,
        playSound: false,
        defaultColor: Colors.red,
        ledColor: Colors.red,
        enableVibration: true,
        vibrationPattern: lowVibrationPattern,
      ),
      NotificationChannel(
        channelGroupKey: 'group_eew-v2',
        channelKey: 'eew-important-v2',
        channelName: '地震速報(重大)',
        channelDescription: '所在地(鄉鎮)預估震度 4 以上',
        importance: NotificationImportance.Max,
        defaultPrivacy: NotificationPrivacy.Public,
        criticalAlerts: true,
        playSound: true,
        soundSource: 'resource://raw/eew',
        defaultRingtoneType: DefaultRingtoneType.Alarm,
        defaultColor: Colors.red,
        ledColor: Colors.red,
        enableVibration: true,
        vibrationPattern: highVibrationPattern,
        locked: true,
      ),
      NotificationChannel(
        channelGroupKey: 'group_eew-v2',
        channelKey: 'eew-general-v2',
        channelName: '地震速報(一般)',
        channelDescription: '所在地(鄉鎮)預估震度 2 以上',
        importance: NotificationImportance.Max,
        defaultPrivacy: NotificationPrivacy.Public,
        criticalAlerts: true,
        playSound: true,
        soundSource: 'resource://raw/eew',
        defaultRingtoneType: DefaultRingtoneType.Alarm,
        defaultColor: Colors.red,
        ledColor: Colors.red,
        enableVibration: true,
        vibrationPattern: mediumVibrationPattern,
      ),
      NotificationChannel(
        channelGroupKey: 'group_eew-v2',
        channelKey: 'eew-silence-v2',
        channelName: '地震速報 (無聲通知)',
        channelDescription: '所在地(鄉鎮)預估震度 1 以上',
        importance: NotificationImportance.Low,
        defaultPrivacy: NotificationPrivacy.Public,
        playSound: false,
        defaultColor: Colors.red,
        ledColor: Colors.red,
        enableVibration: true,
        vibrationPattern: lowVibrationPattern,
      ),
      NotificationChannel(
        channelGroupKey: 'group_eq-v2',
        channelKey: 'int_report-general-v2',
        channelName: '震度速報(一般)',
        channelDescription: '所在地(鄉鎮)實測震度 3 以上',
        importance: NotificationImportance.High,
        defaultPrivacy: NotificationPrivacy.Public,
        playSound: true,
        soundSource: 'resource://raw/int_report',
        defaultColor: Colors.red,
        ledColor: Colors.red,
        enableVibration: true,
        vibrationPattern: highVibrationPattern,
      ),
      NotificationChannel(
        channelGroupKey: 'group_eq-v2',
        channelKey: 'int_report-silence-v2',
        channelName: '震度速報 (無聲通知)',
        channelDescription: '所在地(鄉鎮)實測震度 1 以上',
        importance: NotificationImportance.Low,
        defaultPrivacy: NotificationPrivacy.Public,
        playSound: false,
        defaultColor: Colors.red,
        ledColor: Colors.red,
        enableVibration: true,
        vibrationPattern: lowVibrationPattern,
      ),
      NotificationChannel(
        channelGroupKey: 'group_eq-v2',
        channelKey: 'eq-v2',
        channelName: '強震監視器(一般)',
        channelDescription: '偵測到晃動',
        importance: NotificationImportance.High,
        defaultPrivacy: NotificationPrivacy.Public,
        playSound: true,
        soundSource: 'resource://raw/eq',
        defaultColor: Colors.red,
        ledColor: Colors.red,
        enableVibration: true,
        vibrationPattern: mediumVibrationPattern,
      ),
      NotificationChannel(
        channelGroupKey: 'group_eq-v2',
        channelKey: 'report-general-v2',
        channelName: '地震報告(一般)',
        channelDescription: '地震報告所在地震度 3 以上',
        importance: NotificationImportance.Default,
        defaultPrivacy: NotificationPrivacy.Public,
        playSound: true,
        soundSource: 'resource://raw/report',
        defaultColor: Colors.red,
        ledColor: Colors.red,
        enableVibration: true,
        vibrationPattern: lowVibrationPattern,
      ),
      NotificationChannel(
        channelGroupKey: 'group_eq-v2',
        channelKey: 'report-silence-v2',
        channelName: '地震報告 (無聲通知)',
        channelDescription: '地震報告所在地震度 3 以下的地區',
        groupAlertBehavior: GroupAlertBehavior.Children,
        importance: NotificationImportance.Min,
        defaultPrivacy: NotificationPrivacy.Public,
        playSound: false,
        defaultColor: Colors.red,
        ledColor: Colors.red,
        enableVibration: false,
      ),
      NotificationChannel(
        channelGroupKey: 'group_weather-v2',
        channelKey: 'thunderstorm-general-v2',
        channelName: '雷雨即時訊息(一般)',
        channelDescription: '所在地(鄉鎮)發布雷雨即時訊息或山區暴雨時',
        importance: NotificationImportance.High,
        defaultPrivacy: NotificationPrivacy.Public,
        playSound: true,
        soundSource: 'resource://raw/rain',
        defaultColor: Colors.red,
        ledColor: Colors.red,
        enableVibration: true,
        vibrationPattern: mediumVibrationPattern,
      ),
      NotificationChannel(
        channelGroupKey: 'group_weather-v2',
        channelKey: 'weather_major-important-v2',
        channelName: '天氣警特報(重大)',
        channelDescription: '所在地(鄉鎮)發布紅色燈號之天氣警特報',
        importance: NotificationImportance.Max,
        defaultPrivacy: NotificationPrivacy.Public,
        criticalAlerts: true,
        playSound: true,
        soundSource: 'resource://raw/weather',
        defaultRingtoneType: DefaultRingtoneType.Alarm,
        defaultColor: Colors.red,
        ledColor: Colors.red,
        enableVibration: true,
        vibrationPattern: highVibrationPattern,
        locked: true,
      ),
      NotificationChannel(
        channelGroupKey: 'group_weather-v2',
        channelKey: 'weather_minor-general-v2',
        channelName: '天氣警特報(一般)',
        channelDescription: '所在地(鄉鎮)發布上述除外燈號之天氣警特報',
        importance: NotificationImportance.Default,
        defaultPrivacy: NotificationPrivacy.Public,
        playSound: true,
        soundSource: 'resource://raw/normal',
        defaultColor: Colors.red,
        ledColor: Colors.red,
        enableVibration: true,
        vibrationPattern: mediumVibrationPattern,
      ),
      NotificationChannel(
        channelGroupKey: 'group_info-v2',
        channelKey: 'evacuation_major-important-v2',
        channelName: '避難資訊(重大)',
        channelDescription: '所在地(鄉鎮)發布防空、土石流、淹水或堰塞湖避難警訊時',
        importance: NotificationImportance.Max,
        defaultPrivacy: NotificationPrivacy.Public,
        criticalAlerts: true,
        playSound: true,
        soundSource: 'resource://raw/warn',
        defaultRingtoneType: DefaultRingtoneType.Alarm,
        defaultColor: Colors.red,
        ledColor: Colors.red,
        enableVibration: true,
        vibrationPattern: highVibrationPattern,
        locked: true,
      ),
      NotificationChannel(
        channelGroupKey: 'group_info-v2',
        channelKey: 'evacuation_minor-general-v2',
        channelName: '避難資訊(一般)',
        channelDescription: '所在地(鄉鎮)發布防空、土石流、淹水或堰塞湖避難警訊時',
        importance: NotificationImportance.High,
        defaultPrivacy: NotificationPrivacy.Public,
        playSound: true,
        soundSource: 'resource://raw/warn',
        defaultColor: Colors.red,
        ledColor: Colors.red,
        enableVibration: true,
        vibrationPattern: mediumVibrationPattern,
      ),
      NotificationChannel(
        channelGroupKey: 'group_tsunami-v2',
        channelKey: 'tsunami-important-v2',
        channelName: '海嘯資訊(重大)',
        channelDescription: '海嘯警報發布時，沿海地區鄉鎮',
        importance: NotificationImportance.Max,
        defaultPrivacy: NotificationPrivacy.Public,
        criticalAlerts: true,
        playSound: true,
        soundSource: 'resource://raw/tsunami',
        defaultRingtoneType: DefaultRingtoneType.Alarm,
        defaultColor: Colors.red,
        ledColor: Colors.red,
        enableVibration: true,
        vibrationPattern: highVibrationPattern,
        locked: true,
      ),
      NotificationChannel(
        channelGroupKey: 'group_tsunami-v2',
        channelKey: 'tsunami-general-v2',
        channelName: '海嘯資訊(一般)',
        channelDescription: '海嘯警報發布時，上述除外地區',
        importance: NotificationImportance.Default,
        defaultPrivacy: NotificationPrivacy.Public,
        playSound: true,
        soundSource: 'resource://raw/normal',
        defaultColor: Colors.red,
        ledColor: Colors.red,
        enableVibration: true,
        vibrationPattern: lowVibrationPattern,
      ),
      NotificationChannel(
        channelGroupKey: 'group_tsunami-v2',
        channelKey: 'tsunami-silent-v2',
        channelName: '太平洋海嘯消息 (無聲通知)',
        channelDescription: '地震報告所在地震度 3 以下的地區',
        groupAlertBehavior: GroupAlertBehavior.Children,
        importance: NotificationImportance.Min,
        defaultPrivacy: NotificationPrivacy.Public,
        playSound: false,
        defaultColor: Colors.red,
        ledColor: Colors.red,
        enableVibration: false,
      ),
      NotificationChannel(
        channelGroupKey: 'group_other-v2',
        channelKey: 'announcement-general-v2',
        channelName: '其他通知',
        channelDescription: '發送公告時',
        importance: NotificationImportance.Default,
        defaultPrivacy: NotificationPrivacy.Public,
        playSound: true,
        soundSource: 'resource://raw/info',
        defaultColor: Colors.red,
        ledColor: Colors.red,
        enableVibration: true,
        vibrationPattern: lowVibrationPattern,
      ),
    ],
    channelGroups: [
      NotificationChannelGroup(channelGroupKey: 'group_eew-v2', channelGroupName: '地震速報音效_生效'),
      NotificationChannelGroup(channelGroupKey: 'group_eq-v2', channelGroupName: '地震資訊_生效'),
      NotificationChannelGroup(channelGroupKey: 'group_weather-v2', channelGroupName: '天氣資訊_生效'),
      NotificationChannelGroup(channelGroupKey: 'group_info-v2', channelGroupName: '防災資訊_生效'),
      NotificationChannelGroup(channelGroupKey: 'group_tsunami-v2', channelGroupName: '海嘯資訊_生效'),
      NotificationChannelGroup(channelGroupKey: 'group_other-v2', channelGroupName: '其他_生效'),
    ],
    debug: true,
  );
}
