import 'dart:ui' as ui;

import 'package:dpip/core/logging/log.dart';
import 'package:dpip/core/realtime/app_time.dart';
import 'package:dpip/features/home/presentation/widgets/weather_sky/sky_keyframe.dart';
import 'package:dpip/features/home/presentation/widgets/weather_sky/sky_lut_cache.dart';
import 'package:dpip/features/home/presentation/widgets/weather_sky/card_water_field.dart';
import 'package:dpip/features/home/presentation/widgets/weather_sky/rain_on_glass.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter/scheduler.dart';

/// Puts rain on one card: droplets clinging to its face, and water caught and
/// pooling along its top edge.
///
/// Both halves come from the reference and both are separate from the falling
/// rain in the backdrop. The face gets a droplet shader as a `RenderEffect`
/// (that is [RainOnGlass]); the edge water is a panel particle system (that is
/// [CardWaterField] plus `shaders/weather/card_water.frag`).
///
/// The edge water is drawn the way the engine draws it, in two passes:
///
///   1. Drops accumulate **additively** into an offscreen image — coverage
///      only, no colour. The reference uses an 800 px-tall RGBA16F render
///      texture here.
///   2. That buffer is composited through a shader that applies the alpha
///      threshold and the lighting. Everything that makes it look like water
///      happens in this pass, so drawing the particles straight to the screen —
///      as an earlier version of this did — shows the dots instead.
///
/// Applied per card rather than to the whole sheet: the reference wets the
/// card, not the page, and a refraction filter over an entire scrolling list
/// costs a full-surface pass every frame and warps text nowhere near the rain.
class RainOnCard extends StatefulWidget {
  const RainOnCard({
    super.key,
    required this.child,
    this.intensity = 0.0,
    this.opacity = 1.0,
    this.active = true,
  });

  /// The card. Water is drawn over it, and it is refracted through the
  /// droplets on its face.
  final Widget child;

  /// 0 disables both effects; 1 is a downpour on the card. Picks the grade —
  /// how much water arrives — as the reference's rain level picks a preset.
  final double intensity;

  /// The scene alpha — how visible the whole effect is.
  ///
  /// Separate from [intensity] on purpose: the engine passes its global scene
  /// fade here, full strength whenever the scene shows. Folding the rain grade
  /// into it — as an earlier version did — ran the water at 0.6 × 0.55 ≈ 33%
  /// opacity and washed the whole effect out.
  final double opacity;

  /// Whether the water animates. False holds the last frame.
  final bool active;

  @override
  State<RainOnCard> createState() => _RainOnCardState();
}

class _RainOnCardState extends State<RainOnCard>
    with SingleTickerProviderStateMixin {
  static const String _asset = 'shaders/weather/card_water.frag';

  late final Ticker _ticker = createTicker(_onTick);

  /// Two fields — the reference configures two LiquidFun worlds and always
  /// draws both into one buffer.
  static final (ui.Image, ui.Image) _fallbackSprites = buildParticleSprites();
  late final CardWaterField _primary = CardWaterField(
    spritePos: _fallbackSprites.$1,
    spriteNeg: _fallbackSprites.$2,
  );
  late final CardWaterField _secondary = CardWaterField(
    spritePos: _fallbackSprites.$1,
    spriteNeg: _fallbackSprites.$2,
    seed: 23,
  );

  /// Repaints the water without rebuilding the card beneath it.
  final ValueNotifier<int> _frame = ValueNotifier(0);

  ui.FragmentShader? _shader;
  Duration _last = Duration.zero;
  Size _size = Size.zero;
  double _screenHeight = 0;
  Size _screenSize = Size.zero;

  @override
  void initState() {
    super.initState();
    _load();
    _syncRunning();
  }

  Future<void> _load() async {
    try {
      final program = await ui.FragmentProgram.fromAsset(_asset);
      if (!mounted) return;
      setState(() => _shader = program.fragmentShader());
    } catch (error, stackTrace) {
      Log.handle(error, stackTrace, 'Failed to load shader $_asset');
    }
    // Swap the procedural stand-in for the baked sprite the moment the two
    // source textures decode. Both are generated by `tool/gen_particle_
    // sprites.py` — the kernel is a blurred disc, the normal map an analytic
    // hemisphere, so they are the same *functions* the engine samples.
    try {
      final kernel = await _decodeAsset(
        'assets/weather/particles/particle_blurred.webp',
      );
      final normalMap = await _decodeAsset(
        'assets/weather/particles/drop_normal.webp',
      );
      final (pos, neg) = await bakeParticleSprites(
        kernel: kernel,
        normalMap: normalMap,
      );
      kernel.dispose();
      normalMap.dispose();
      if (!mounted) {
        pos.dispose();
        neg.dispose();
        return;
      }
      _primary.spritePos = pos;
      _primary.spriteNeg = neg;
      _secondary.spritePos = pos;
      _secondary.spriteNeg = neg;
    } catch (error, stackTrace) {
      Log.handle(error, stackTrace, 'Failed to bake the drop sprite');
    }
  }

  static Future<ui.Image> _decodeAsset(String key) async {
    final data = await rootBundle.load(key);
    final codec = await ui.instantiateImageCodec(data.buffer.asUint8List());
    final frame = await codec.getNextFrame();
    codec.dispose();
    return frame.image;
  }

  @override
  void didUpdateWidget(RainOnCard oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.active != widget.active ||
        (oldWidget.intensity > 0.001) != (widget.intensity > 0.001) ||
        (oldWidget.opacity > 0.004) != (widget.opacity > 0.004)) {
      _syncRunning();
    }
  }

  void _syncRunning() {
    final draining = _primary.liveCount > 0 || _secondary.liveCount > 0;
    final visible = widget.opacity > 0.004;
    if (widget.active && visible && (widget.intensity > 0.001 || draining)) {
      if (!_ticker.isActive) {
        _last = Duration.zero;
        _ticker.start();
      }
    } else {
      _ticker.stop();
      if (widget.intensity <= 0.001) {
        _primary.clear();
        _secondary.clear();
      }
    }
  }

  /// The position gate: the panel water switches off entirely once the card
  /// has been scrolled up into the top fifth of the screen.
  ///
  /// The reference feeds the panel's on-screen y into a comparison against a
  /// fixed reference height — the water stops once `y` drops below 30 % of it.
  /// That height defaults to 1714 against a 2400 px screen, so the cut-off
  /// lands at 21.4 % of the screen height.
  ///
  /// The gate guards the particle draw *and* the accumulate-and-blur, so
  /// nothing renders at all — water has no business pooling on a card that is
  /// about to slide under the toolbar.
  static const double _gateReferenceHeight = 1714 / 2400;
  static const double _gateFraction = 0.3;

  /// Where the card's top edge currently sits, in logical pixels from the top
  /// of the window. Null before the first layout.
  double? _cardTopY;
  bool _gateOpen = true;

  /// World gravity is multiplied by **1.5 while the card is travelling up the
  /// screen**, so water thrown off the lip is pulled back down instead of
  /// trailing behind a scroll.
  ///
  /// The reference compares the card's new position against the last one and
  /// switches to the boosted mode when it moved more than 5 px, applying the
  /// multiplier on every timer tick's `world.setGravity`. The 5 px is against
  /// the same 2400 px reference screen.
  double _gravityScale = 1.0;
  static const double _scrollGravityScale = 1.5;
  static const double _scrollThresholdRatio = 5 / 2400;

  /// Re-reads the card's position and applies the gate. Cheap enough to run
  /// per tick: the reference re-evaluates it on every scroll callback.
  void _syncPositionGate() {
    final box = context.findRenderObject() as RenderBox?;
    if (box == null || !box.hasSize) return;
    final previous = _cardTopY;
    _cardTopY = box.localToGlobal(Offset.zero).dy;
    // The reference compares a quantity that grows as the card rises — so the
    // boosted mode is the card moving *up*, not any movement at all.
    _gravityScale =
        previous != null &&
            previous - _cardTopY! > _scrollThresholdRatio * _screenHeight
        ? _scrollGravityScale
        : 1.0;
    final open =
        _cardTopY! >= _gateFraction * _gateReferenceHeight * _screenHeight;
    if (open == _gateOpen) return;
    setState(() => _gateOpen = open);
  }

  void _onTick(Duration elapsed) {
    final dt = _last == Duration.zero
        ? 0.0
        : (elapsed - _last).inMicroseconds / 1e6;
    _last = elapsed;
    // Width only. The card sits in a ListView, so its height is unbounded at
    // layout time and `Size.isEmpty` was true on every frame — which silently
    // skipped the whole simulation and left the edge dry.
    if (dt <= 0 || _size.width <= 0) return;

    _syncPositionGate();

    final intensity = widget.intensity.clamp(0.0, 1.0);
    final grade = _gradeFor(intensity);
    _primary.update(
      dt,
      width: _size.width,
      screenHeight: _screenHeight,
      intensity: intensity,
      preset: grade.$1,
      gravityScale: _gravityScale,
    );
    _secondary.update(
      dt,
      width: _size.width,
      screenHeight: _screenHeight,
      intensity: intensity,
      preset: grade.$2,
      gravityScale: _gravityScale,
    );
    _frame.value++;

    if (intensity <= 0.001 &&
        _primary.liveCount == 0 &&
        _secondary.liveCount == 0) {
      _ticker.stop();
    }
  }

  /// Maps our 0→1 intensity onto the reference's rain grades.
  ///
  /// **Both** worlds run at every grade — the reference's loop configures world 0 and
  /// world 1 identically for grades 0/1 and differently only for 2/3, and
  /// The reference always draws both. Idling the second world at the lighter grades,
  /// as an earlier version did, halves the water.
  static (CardWaterPreset, CardWaterPreset) _gradeFor(double intensity) {
    if (intensity >= 0.7) {
      return (CardWaterPreset.heavy, CardWaterPreset.heavySecondary);
    }
    if (intensity >= 0.35) {
      return (CardWaterPreset.moderate, CardWaterPreset.moderate);
    }
    return (CardWaterPreset.light, CardWaterPreset.light);
  }

  /// `specularIntensity` on the panel branch: 1.2 at night, 1.0 by day.
  static const double _specularDay = 1.0;
  static const double _specularNight = 1.2;

  /// Drawn diameter of one drop and the metaball's alpha cut, together —
  /// The reference picks the pair from the screen aspect: tall screens (h/w ≥ 2,
  /// the normal phone) get 5.0 px drops with the 0.6 cut, squarer screens
  /// smaller drops with a lower cut.
  ///
  /// Those are **buffer** pixels, not logical ones: the particle pass renders
  /// into an 800-tall render texture that stands for the whole screen, so a
  /// drop covers `size/800` of the screen's height whatever the device.
  (double, double) get _pointSizeAndThreshold {
    final w = _screenSize.width;
    final h = _screenSize.height;
    if (w <= 0 || h <= 0) return (5.0, 0.6);
    final scale = h / CardWaterField.bufferHeight;
    if (h / w >= 2.0) return (5.0 * scale, 0.6);
    if (h > w) return (3.3 * scale, 0.3);
    return (3.7 * scale, 0.3);
  }

  @override
  void dispose() {
    _ticker.dispose();
    _frame.dispose();
    _shader?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    _screenSize = MediaQuery.sizeOf(context);
    _screenHeight = _screenSize.height;
    // The reference's night flag is `hour >= 15 || hour <= 4` — and that hour is
    // the scene's position on its 24-keyframe day ring, where ~15 is dusk and
    // ~4 is dawn. DPIP has the same mapping; the theme's brightness (used here
    // before) is unrelated to the sun.
    final wall = AppTime.utc8;
    final key = keyframePosition(
      wall.hour + wall.minute / 60.0,
      frameCount: 24,
    );
    final night = key >= 15.0 || key <= 4.0;
    final (pointSize, threshold) = _pointSizeAndThreshold;
    return LayoutBuilder(
      builder: (context, constraints) {
        _size = Size(
          constraints.maxWidth,
          constraints.hasBoundedHeight ? constraints.maxHeight : 0,
        );
        // Height may legitimately be 0 here — see [_onTick].
        return Stack(
          // Water sits above the card's top edge and must not be cut off.
          clipBehavior: Clip.none,
          children: [
            RainOnGlass(
              intensity: widget.intensity,
              opacity: widget.opacity,
              active: widget.active,
              child: widget.child,
            ),
            Positioned.fill(
              child: IgnorePointer(
                child: RepaintBoundary(
                  child: CustomPaint(
                    painter: _CardWaterPainter(
                      primary: _primary,
                      secondary: _secondary,
                      shader: _shader,
                      // Also repaints when the sky re-bakes, so the water's
                      // ambient follows the backdrop it falls out of.
                      repaint: Listenable.merge([
                        _frame,
                        SkyLutCache.panelAmbient,
                      ]),
                      opacity: widget.opacity.clamp(0.0, 1.0),
                      night: night,
                      screenHeight: _screenHeight,
                      pointSize: pointSize,
                      threshold: threshold,
                      screenWidth: _screenSize.width,
                      gateOpen: _gateOpen,
                    ),
                  ),
                ),
              ),
            ),
          ],
        );
      },
    );
  }
}

class _CardWaterPainter extends CustomPainter {
  _CardWaterPainter({
    required this.primary,
    required this.secondary,
    required this.shader,
    required Listenable repaint,
    required this.opacity,
    required this.night,
    required this.screenHeight,
    required this.screenWidth,
    required this.gateOpen,
    required this.pointSize,
    required this.threshold,
  }) : super(repaint: repaint);

  final CardWaterField primary;
  final CardWaterField secondary;
  final ui.FragmentShader? shader;
  final double opacity;
  final bool night;
  final double screenHeight;
  final double screenWidth;

  /// The position gate — false once the card is too high on screen; both
  /// passes are skipped, not just the draw.
  final bool gateOpen;
  final double pointSize;
  final double threshold;

  /// The separable 5-tap blur the reference runs between the particle pass and
  /// the composite, as an equivalent gaussian.
  ///
  /// Taps sit at ±0.7 and ±0.35 of `uBlurBufferSize` with weights
  /// .164/.217/.238, so σ is `sqrt(2·(0.164·0.7² + 0.217·0.35²))` = 0.4625 of
  /// that step. The step is the load-bearing part: the reference computes it
  /// as `1/((w·355)/h)` **while both fields are still 1**, and only assigns the
  /// buffer's width and height afterwards — so the aspect correction is dead
  /// code and *both* axes get a flat 1/355 in **UV**.
  ///
  /// A UV step is not a pixel step. On the 800-tall buffer that is 1.04 px
  /// vertically but only `1.04·W/H` horizontally — the blur is 2.2x wider
  /// down the screen than across it, and reading it as one isotropic 0.46 px
  /// (as an earlier version did) leaves each drop far too sharp and far too
  /// much of it above the alpha cut.
  static const double _blurStepUv = 1 / 355;
  static const double _blurSigmaUv = 0.46253 * _blurStepUv;

  double get _sigmaX => _blurSigmaUv * screenWidth;
  double get _sigmaY => _blurSigmaUv * screenHeight;

  /// One signed half of the accumulation — see [CardWaterField.paintCoverage].
  ui.Image _accumulate(
    Size fieldSize,
    double headroom, {
    required bool negative,
  }) {
    final recorder = ui.PictureRecorder();
    final offscreen = Canvas(recorder);
    offscreen.saveLayer(
      Offset.zero & fieldSize,
      Paint()
        ..imageFilter = ui.ImageFilter.blur(sigmaX: _sigmaX, sigmaY: _sigmaY),
    );
    offscreen.translate(0, headroom);
    primary.paintCoverage(offscreen, dropSize: pointSize, negative: negative);
    secondary.paintCoverage(offscreen, dropSize: pointSize, negative: negative);
    offscreen.restore();
    return recorder.endRecording().toImageSync(
      fieldSize.width.ceil(),
      fieldSize.height.ceil(),
    );
  }

  @override
  void paint(Canvas canvas, Size size) {
    final shader = this.shader;
    if (shader == null || opacity <= 0.004 || !gateOpen) return;
    if (primary.liveCount == 0 && secondary.liveCount == 0) return;
    if (size.isEmpty) return;

    // Pass 1: accumulate both signed halves, blurred as the engine blurs its
    // buffer. Spans the card plus the whole fall above it.
    final headroom = CardWaterField.spawnHeadroom(screenHeight);
    final fieldSize = Size(size.width, size.height + headroom);
    final pos = _accumulate(fieldSize, headroom, negative: false);
    final neg = _accumulate(fieldSize, headroom, negative: true);

    // Pass 2: reassemble the signed sum, light it, hard-cut it.
    // `J.s()` passes `Time().hour` — the local wall-clock hour.
    final hour = AppTime.utc8.hour.toDouble();
    var i = 0;
    void set(double v) => shader.setFloat(i++, v);
    set(fieldSize.width);
    set(fieldSize.height);
    // The sky at the panel band — the reference's `uBgLightTex` row. Until the first
    // bake lands, a rainy overcast grey-blue stands in.
    final ambient = SkyLutCache.panelAmbient.value ?? const Color(0xFF5C6B7E);
    set(ambient.r);
    set(ambient.g);
    set(ambient.b);
    set(night ? _specularNight : _specularDay);
    // The accumulation is scaled to dodge 8-bit saturation; the cut scales
    // with it so the metaball shape is untouched.
    set(threshold * CardWaterField.accumulationScale);
    set(opacity);
    set(hour);
    shader.setImageSampler(0, pos);
    shader.setImageSampler(1, neg);

    canvas.save();
    canvas.translate(0, -headroom);
    canvas.drawRect(
      Rect.fromLTWH(0, 0, fieldSize.width, fieldSize.height),
      Paint()..shader = shader,
    );
    canvas.restore();
    pos.dispose();
    neg.dispose();
  }

  static const double _specularDay = _RainOnCardState._specularDay;
  static const double _specularNight = _RainOnCardState._specularNight;

  @override
  bool shouldRepaint(covariant _CardWaterPainter oldDelegate) =>
      oldDelegate.opacity != opacity ||
      oldDelegate.night != night ||
      oldDelegate.shader != shader ||
      oldDelegate.pointSize != pointSize ||
      oldDelegate.threshold != threshold ||
      oldDelegate.screenHeight != screenHeight ||
      oldDelegate.screenWidth != screenWidth ||
      oldDelegate.gateOpen != gateOpen;
}
