import 'dart:math' as math;
import 'dart:ui' as ui;

import 'package:dpip/core/logging/log.dart';
import 'package:dpip/core/platform/device_info.dart';
import 'package:dpip/core/platform/render_tier.dart';
import 'package:dpip/core/realtime/app_time.dart';
import 'package:dpip/core/settings/sky_time_mode.dart';
import 'package:dpip/core/settings/weather_mode.dart';
import 'package:dpip/features/home/presentation/widgets/weather_sky/precipitation_field.dart';
import 'package:dpip/features/home/presentation/widgets/weather_sky/sky_clouds.dart';
import 'package:dpip/features/home/presentation/widgets/weather_sky/sky_keyframe.dart';
import 'package:dpip/features/home/presentation/widgets/weather_sky/sky_keyframe_data.dart';
import 'package:dpip/features/home/presentation/widgets/weather_sky/sky_lut_cache.dart';
import 'package:dpip/features/home/presentation/widgets/weather_sky/solar_time.dart';
import 'package:dpip/features/home/presentation/widgets/weather_sky/weather_sky_painter.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;

/// GPU-rendered layered sky backdrop, ported from the reference engine.
///
/// The scene is driven the way the original is: a ring of authored keyframes
/// per weather type (`sky_keyframe_data.dart`) supplies the atmosphere, and a three-stage scattering pipeline
/// (`shaders/sky/`) bakes that into two lookup tables the screen pass simply
/// reads. There is no simulated sun — `sunAngleY` *is* the sky LUT's u
/// coordinate. The ring is anchored to the real sunrise and sunset for the
/// viewer's latitude, so dawn keyframes land at dawn year-round.
///
/// Clouds are authored volumetric sprites with baked normal maps
/// (`assets/weather/clouds/`, generated by `tool/gen_cloud_sprites.py`), lit by
/// sampling the sky LUT — the environment-light model, and the reason
/// cloud colour always agrees with the sky behind it.
///
/// Cost is controlled by structure: the scattering integral runs only when the
/// resolved keyframe changes (minutes apart, not frames), layers render at
/// [_renderScale] and are upscaled, and each gates itself on its own control.
///
/// [mode] forces a look; [active] holds the last frame when the backdrop is
/// off-screen to save GPU.
class WeatherSkyBackground extends StatefulWidget {
  /// Which weather look to render.
  final WeatherMode mode;

  /// Overrides the look's default rain amount (0..1 on the painter's ladder:
  /// 0.321 小雨 → 1.0 暴雨) when a live code carries one; `null` keeps the
  /// look's own default.
  final double? rainIntensity;

  /// Overrides the look's default snow amount (0..1); `null` keeps the look's.
  final double? snowIntensity;

  /// Whether the animation should run.
  final bool active;

  /// Viewer latitude, for anchoring the keyframe ring to the real day.
  final double latitude;

  /// Viewer longitude.
  final double longitude;

  /// Relative humidity 0..1, which blends each keyframe's atmosphere ramps.
  final double humidity;

  /// Pins the sky to a point in the day, or follows the clock on
  /// [SkyTimeMode.auto].
  final SkyTimeMode timeMode;

  const WeatherSkyBackground({
    super.key,
    this.mode = WeatherMode.auto,
    this.rainIntensity,
    this.snowIntensity,
    this.active = true,
    this.latitude = kTaiwanLatitude,
    this.longitude = kTaiwanLongitude,
    this.humidity = 0.65,
    this.timeMode = SkyTimeMode.auto,
  });

  @override
  State<WeatherSkyBackground> createState() => _WeatherSkyBackgroundState();
}

class _WeatherSkyBackgroundState extends State<WeatherSkyBackground>
    with SingleTickerProviderStateMixin {
  /// Internal render resolution as a fraction of the widget's size.
  ///
  /// The reference rasterises everything before layer 8 — sky, galaxy, clouds
  /// — at **half** device resolution and the deferred layers at 0.75, then
  /// upscales. This port draws every layer in one pass, so a
  /// single scale has to serve both; 0.75 matches the precipitation layers,
  /// which are the ones that suffer most from being softened, and leaves the
  /// cloud deck only slightly sharper than the original. The low tier draws
  /// at 0.6 — a softer upscale, not a lower frame rate.
  static const double _renderScaleHigh = 0.75;
  static const double _renderScaleLow = 0.6;

  /// The device tier, resolved once before the particles are built (their
  /// pools depend on it). Null only while the first tier probe is in flight;
  /// the backdrop holds its flat fallback colour until [_load] lands.
  RenderTier? _tier;

  /// Number of cloud sprites in `assets/weather/clouds/`.
  static const int _spriteCount = 12;

  static const List<String> _bakeAssets = [
    'shaders/sky/transmittance.frag',
    'shaders/sky/sky_lut.frag',
  ];

  static const List<String> _layerAssets = [
    WeatherSkyPainter.nightAsset,
    WeatherSkyPainter.cloudsAsset,
    WeatherSkyPainter.lightningAsset,
    WeatherSkyPainter.sunFlareAsset,
    WeatherSkyPainter.rainbowAsset,
  ];

  final Stopwatch _clock = Stopwatch();
  late final AnimationController _ticker = AnimationController(
    duration: const Duration(seconds: 60),
    vsync: this,
  );

  final Map<String, ui.FragmentShader> _shaders = {};
  final List<ui.Image> _sprites = [];
  final List<ui.Image> _sunTextures = [];
  SkyLutCache? _lutCache;
  PrecipitationField? _rain;
  PrecipitationField? _snow;

  /// Wall-clock of the previous frame, for the particle integration step.
  double _lastFrameSeconds = 0;

  /// The painter instance from the last animated frame, reused while the
  /// animation is stopped so rebuilds of the subtree above don't repaint the
  /// sky (see the [CustomPaint] construction in build).
  WeatherSkyPainter? _lastPainter;

  /// UTC day of the cached [_sun] / [_moon] (sunrise/sunset move ~1 min
  /// per day; the moon phase by ~2.5 % per day — frame-level recomputation is
  /// pure waste, and day-level caching keeps them exact for a whole session).
  int _dayKey = -1;
  ({double sunrise, double sunset}) _sun = (sunrise: 5.6, sunset: 18.4);
  double _moon = 0;

  /// Local minute of the cached [_position] / [_sky]. The keyframe ring only
  /// advances ~17 frames over a day, so one tick a minute is ~1/85,000 of the
  /// ring — far below the LUT's own resolution. Batching to the minute means
  /// the scattering bake (256×256 + 256×141 rasterise + CPU readback +
  /// gradient rebuild) runs once a minute instead of once a second, which is
  /// the difference between a cheap backdrop and one that drops a frame
  /// mid-animation on a low-end GPU.
  int _minuteKey = -1;
  double _position = 0;
  ResolvedSky? _sky;

  @override
  void initState() {
    super.initState();
    _syncRunning();
    _init();
  }

  /// Resolves the device tier, then loads shaders/sprites/particles — the
  /// particle pools and render scale depend on the tier, so it must land
  /// first. A tier probe failure keeps full quality (never degrade an
  /// experience on a measurement we didn't get).
  Future<void> _init() async {
    RenderTier tier;
    try {
      tier = renderTierFor(await DeviceInfoService.load());
    } catch (error, stackTrace) {
      Log.handle(error, stackTrace, 'Device tier probe failed');
      tier = RenderTier.high;
    }
    if (!mounted) return;
    _tier = tier;
    await _load();
  }

  Future<void> _load() async {
    final layers = <String, ui.FragmentShader>{};
    final bakers = <String, ui.FragmentShader>{};

    for (final asset in [..._bakeAssets, ..._layerAssets]) {
      try {
        final program = await ui.FragmentProgram.fromAsset(asset);
        final shader = program.fragmentShader();
        if (_bakeAssets.contains(asset)) {
          bakers[asset] = shader;
        } else {
          layers[asset] = shader;
        }
      } catch (error, stackTrace) {
        Log.handle(error, stackTrace, 'Failed to load shader $asset');
      }
    }

    ui.Image? rainAtlas;
    ui.Image? snowAtlas;
    for (final entry in const [
      ('assets/weather/particles/rain_drop.webp', true),
      ('assets/weather/particles/snow_flake.webp', false),
    ]) {
      try {
        final data = await rootBundle.load(entry.$1);
        final codec = await ui.instantiateImageCodec(data.buffer.asUint8List());
        final image = (await codec.getNextFrame()).image;
        if (entry.$2) {
          rainAtlas = image;
        } else {
          snowAtlas = image;
        }
      } catch (error, stackTrace) {
        Log.handle(
          error,
          stackTrace,
          'Failed to load particle sprite ${entry.$1}',
        );
      }
    }

    final sunTex = <ui.Image>[];
    for (final path in const [
      'assets/weather/sky/sun_profile.webp',
      'assets/weather/sky/sun_rays.webp',
      'assets/weather/sky/annulus.webp',
    ]) {
      try {
        final data = await rootBundle.load(path);
        final codec = await ui.instantiateImageCodec(data.buffer.asUint8List());
        sunTex.add((await codec.getNextFrame()).image);
      } catch (error, stackTrace) {
        Log.handle(error, stackTrace, 'Failed to load sun texture $path');
      }
    }

    final sprites = <ui.Image>[];
    for (var i = 0; i < _spriteCount; i++) {
      final path = 'assets/weather/clouds/${i.toString().padLeft(2, '0')}.webp';
      try {
        final data = await rootBundle.load(path);
        final codec = await ui.instantiateImageCodec(data.buffer.asUint8List());
        sprites.add((await codec.getNextFrame()).image);
      } catch (error, stackTrace) {
        Log.handle(error, stackTrace, 'Failed to load cloud sprite $path');
      }
    }

    if (!mounted) {
      for (final s in [...layers.values, ...bakers.values]) {
        s.dispose();
      }
      for (final image in sprites) {
        image.dispose();
      }
      rainAtlas?.dispose();
      snowAtlas?.dispose();
      for (final t in sunTex) {
        t.dispose();
      }
      return;
    }

    final transmittance = bakers[_bakeAssets[0]];
    final skyLut = bakers[_bakeAssets[1]];

    setState(() {
      _disposeResources();
      _shaders
        ..addAll(layers)
        ..addAll(bakers);
      _sprites.addAll(sprites);
      _sunTextures.addAll(sunTex);
      // Without both bake shaders there is no sky; the fallback colour shows.
      _lutCache = (transmittance != null && skyLut != null)
          ? SkyLutCache(transmittance, skyLut)
          : null;
      // The rain atlas packs four width variants; snow is a single cell.
      final lowEnd = _tier == RenderTier.low;
      _rain = rainAtlas == null
          ? null
          : PrecipitationField(
              atlas: rainAtlas,
              // The reference's storm preset pool; lighter rain uses proportionally
              // fewer, which is how it expresses intensity. The low tier caps at
              // the 大雨 pool — the storm's full 1792-drop budget is the single
              // most expensive layer a low-end GPU can be asked to draw.
              capacity: lowEnd ? 1024 : 1792,
              variants: 4,
              cell: const Size(32, 68),
              seed: 7,
            );
      _snow = snowAtlas == null
          ? null
          : PrecipitationField(
              atlas: snowAtlas,
              capacity: lowEnd ? 640 : 900,
              cell: const Size(40, 40),
              tumble: true,
              seed: 11,
            );
    });
  }

  void _disposeResources() {
    _lutCache?.dispose();
    _lutCache = null;
    for (final shader in _shaders.values) {
      shader.dispose();
    }
    _shaders.clear();
    for (final image in _sprites) {
      image.dispose();
    }
    _sprites.clear();
    for (final t in _sunTextures) {
      t.dispose();
    }
    _sunTextures.clear();
    _rain?.atlas.dispose();
    _snow?.atlas.dispose();
    _rain = null;
    _snow = null;
  }

  void _syncRunning() {
    if (widget.active) {
      if (!_clock.isRunning) _clock.start();
      _ticker.repeat();
    } else {
      _clock.stop();
      _ticker.stop();
    }
  }

  @override
  void didUpdateWidget(WeatherSkyBackground oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.active != widget.active) _syncRunning();
  }

  @override
  void dispose() {
    _ticker.dispose();
    _disposeResources();
    _clock.stop();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final cache = _lutCache;
    if (cache == null || _shaders.length < _layerAssets.length) {
      return ColoredBox(color: _fallbackColour(widget.mode));
    }

    return LayoutBuilder(
      builder: (context, constraints) {
        final painted = AnimatedBuilder(
          animation: _ticker,
          builder: (context, _) {
            final frame = _buildFrame();
            // Re-bakes only when the resolved keyframe has actually moved.
            cache.update(frame.sky);

            // Clamped so a dropped frame or a resume from background does not
            // teleport every particle down the screen in one step.
            final dt = (frame.time - _lastFrameSeconds).clamp(0.0, 1 / 20);
            _lastFrameSeconds = frame.time;

            // While the animation is stopped (`active: false` — the sheet is
            // collapsed, or the sky sits under the scroll blur), the scene
            // cannot change, so a rebuilt painter is byte-identical. Handing
            // the *same* painter instance back lets RenderCustomPaint skip
            // the repaint on those rebuilds (it compares by identity) — the
            // scroll-driven rebuilds of the subtree above this widget
            // (`_ScrollBlurredWeather`) then cost an element update instead
            // of a full-screen shader stack re-render on every scroll tick.
            final moving = widget.active && dt > 0;
            final painter = moving || _lastPainter == null
                ? WeatherSkyPainter(
                    shaders: _shaders,
                    lutCache: cache,
                    cloudSprites: _sprites,
                    sunTextures: _sunTextures,
                    frame: frame,
                    rainField: _rain,
                    snowField: _snow,
                    dt: dt,
                  )
                : _lastPainter!;
            _lastPainter = painter;
            return CustomPaint(size: Size.infinite, painter: painter);
          },
        );

        if (!constraints.hasBoundedWidth || !constraints.hasBoundedHeight) {
          return painted;
        }

        // Rasterise small and let the transform upscale bilinearly.
        final scale = _tier == RenderTier.low
            ? _renderScaleLow
            : _renderScaleHigh;
        return ClipRect(
          child: Align(
            alignment: Alignment.topLeft,
            child: Transform.scale(
              scale: 1 / scale,
              alignment: Alignment.topLeft,
              filterQuality: FilterQuality.low,
              child: SizedBox(
                width: (constraints.maxWidth * scale).ceilToDouble(),
                height: (constraints.maxHeight * scale).ceilToDouble(),
                child: painted,
              ),
            ),
          ),
        );
      },
    );
  }

  SkyFrame _buildFrame() {
    final utc = AppTime.utc;
    final local = AppTime.utc8;
    final time = _clock.elapsedMilliseconds / 1000.0;

    final look = _lookFor(widget.mode);
    final frames = look.keyframes;
    // A live code's continuous channels win over the look's defaults — e.g.
    // 106 有雨 keeps the rain look's keyframes but runs 0.35 instead of the
    // fixed 小雨 rung. Snow is a separate field, so a rain-snow mix renders
    // both.
    final rain = widget.rainIntensity ?? look.rain;
    final snow = widget.snowIntensity ?? look.snow;

    _syncSky(utc, local, frames);

    return SkyFrame(
      time: time,
      sky: _sky!,
      cloudLayout: look.layout,
      cloudCoverage: look.coverage,
      rain: rain,
      snow: snow,
      fog: look.fog,
      rainbow: look.rainbow,
      wind: look.wind,
      lightning: look.lightning ? _lightningAt(time) : LightningFrame.none,
      moonPhase: _moon,
      keyframePosition: _position,
    );
  }

  /// Recomputes the sky pieces that have their own cadence — the sun anchor and
  /// moon phase once a day, the keyframe ring position once a minute — and
  /// caches them for the per-frame [SkyFrame] assembly.
  ///
  /// This is what keeps the per-frame cost of `_buildFrame` down to the parts
  /// that genuinely move every frame ([_lightningAt], particle time): before
  /// this, the ephemeris ran (and the LUT re-baked, see [_minuteKey]) on every
  /// tick.
  void _syncSky(DateTime utc, DateTime local, List<SkyKeyframe> frames) {
    final dayKey = utc.millisecondsSinceEpoch ~/ 86400000;
    if (dayKey != _dayKey) {
      _dayKey = dayKey;
      // Anchor the ring to the day's real sunrise and sunset, so dawn keyframes
      // land at dawn in December as well as June.
      _sun = sunTimes(
        utc,
        latitude: widget.latitude,
        longitude: widget.longitude,
      );
      _moon = _moonPhase(utc);
    }
    final minuteKey = local.millisecondsSinceEpoch ~/ 60000;
    if (minuteKey != _minuteKey) {
      _minuteKey = minuteKey;
      final hour =
          skyTimeHour(widget.timeMode) ?? (local.hour + local.minute / 60.0);
      _position = keyframePosition(
        hour,
        frameCount: frames.length,
        sunrise: _sun.sunrise,
        sunset: _sun.sunset,
      );
      _sky = resolveSky(frames, position: _position, humidity: widget.humidity);
    }
  }

  Color _fallbackColour(WeatherMode mode) => switch (mode) {
    WeatherMode.thunderstorm => const Color(0xFF2A2F3A),
    WeatherMode.rain => const Color(0xFF44505F),
    WeatherMode.fog => const Color(0xFF8A9099),
    _ => const Color(0xFF3F6DAE),
  };
}

typedef _Look = ({
  List<SkyKeyframe> keyframes,
  CloudLayout layout,
  double coverage,
  double rain,
  double snow,
  double fog,
  double rainbow,
  double wind,
  bool lightning,
});

/// Maps a [WeatherMode] onto a the reference weather type and its layer controls.
///
/// The keyframe tables cover all 14 of the engine's weather types; the five
/// user-facing modes pick from them, so adding a mode later is a table entry
/// rather than new artwork.
_Look _lookFor(WeatherMode mode) => switch (mode) {
  // Until a live feed drives it, `auto` is Taiwan's typical humid, lightly
  // clouded sky.
  WeatherMode.auto => (
    keyframes: cloudyKeyframes,
    layout: CloudLayout.scattered,
    coverage: 0.55,
    rain: 0.0,
    snow: 0.0,
    fog: 0.0,
    rainbow: 0.0,
    wind: 0.25,
    lightning: false,
  ),
  WeatherMode.clear => (
    keyframes: sunnyKeyframes,
    layout: CloudLayout.fair,
    coverage: 0.35,
    rain: 0.0,
    snow: 0.0,
    fog: 0.0,
    rainbow: 0.0,
    wind: 0.18,
    lightning: false,
  ),
  WeatherMode.cloudy => (
    keyframes: cloudyKeyframes,
    layout: CloudLayout.scattered,
    coverage: 0.85,
    rain: 0.0,
    snow: 0.0,
    fog: 0.0,
    rainbow: 0.0,
    wind: 0.30,
    lightning: false,
  ),
  WeatherMode.overcast => (
    keyframes: overcastKeyframes,
    layout: CloudLayout.overcast,
    coverage: 1.0,
    rain: 0.0,
    snow: 0.0,
    fog: 0.05,
    rainbow: 0.0,
    wind: 0.20,
    lightning: false,
  ),
  WeatherMode.snow => (
    keyframes: snowyMediumKeyframes,
    layout: CloudLayout.overcast,
    coverage: 0.95,
    rain: 0.0,
    snow: 0.7,
    fog: 0.10,
    rainbow: 0.0,
    wind: 0.30,
    lightning: false,
  ),
  // No sand shader yet — the sandy keyframes plus a heavy dust-coloured haze
  // stand in, so the mode is at least testable.
  WeatherMode.sand => (
    keyframes: sandyHeavyKeyframes,
    layout: CloudLayout.overcast,
    coverage: 0.65,
    rain: 0.0,
    snow: 0.0,
    fog: 0.9,
    rainbow: 0.0,
    wind: 0.55,
    lightning: false,
  ),
  WeatherMode.rain => (
    keyframes: rainyMediumKeyframes,
    layout: CloudLayout.rain,
    coverage: 1.0,
    // The reference expresses rain intensity almost entirely through particle *count*,
    // and it has four discrete presets: 576 / 1024 / 1472 / 1792 drops for
    // 小雨 / 中雨 / 大雨 / 暴雨. Against the storm-sized pool below that is
    // 0.321 / 0.571 / 0.821 / 1.0, so the plain rain backdrop sits on the
    // 小雨 rung — the same rung the shipped capture runs at.
    rain: 0.321,
    snow: 0.0,
    fog: 0.08,
    rainbow: 0.0,
    wind: 0.40,
    lightning: false,
  ),
  WeatherMode.fog => (
    keyframes: foggyKeyframes,
    layout: CloudLayout.overcast,
    coverage: 0.7,
    rain: 0.0,
    snow: 0.0,
    fog: 0.85,
    rainbow: 0.0,
    wind: 0.10,
    lightning: false,
  ),
  WeatherMode.thunderstorm => (
    keyframes: rainyExtremeKeyframes,
    layout: CloudLayout.rain,
    coverage: 1.0,
    // The 暴雨 rung — the full 1792-drop pool.
    rain: 1.0,
    snow: 0.0,
    fog: 0.12,
    rainbow: 0.0,
    wind: 0.65,
    lightning: true,
  ),
};

/// Approximate lunar phase, 0 new → 0.5 full → 1 new.
///
/// A linear count of synodic months since a known new moon. Good to about a
/// day, which for a moon a few dozen pixels across is exact.
double _moonPhase(DateTime utc) {
  const synodicMonth = 29.530588853;
  final days =
      utc.difference(DateTime.utc(2000, 1, 6, 18, 14)).inMinutes / 1440.0;
  final phase = (days / synodicMonth) % 1.0;
  return phase < 0 ? phase + 1.0 : phase;
}

/// The lightning envelope at [time] seconds.
///
/// Strikes are quantised into windows and hash-gated so only some fire, giving
/// an irregular rhythm. The window is deliberately long: a disaster-prevention
/// app must not strobe, and the shader caps flash brightness on top of this.
LightningFrame _lightningAt(double time) {
  const period = 4.2;
  final window = (time / period).floorToDouble();
  if (_hash01(window) > 0.42) return LightningFrame.none;

  final age = time - window * period;
  if (age > 1.2) return LightningFrame.none;

  final strength = 0.55 + 0.45 * _hash01(window + 7.0);
  return LightningFrame(
    age: age,
    flash: strength,
    bolt: strength,
    seed: window,
  );
}

double _hash01(double n) {
  final x = math.sin(n * 127.1) * 43758.5453;
  return x - x.floorToDouble();
}
