/// Weather glyphs, from the bundled `DpipWeatherIcons` subset font.
///
/// **Generated by `tool/gen/weather_icons.py` — do not edit by hand.**
/// Every codepoint here was read from Google's `.codepoints` manifest in the
/// same run that built the font, because the alternative is guessing: this file
/// previously declared `rainy` as `0xf07c2`, which is `Icons.severe_cold` in
/// Flutter's bundled font, and so drew a snowflake on every rainy hour.
///
/// The font is Material Symbols Outlined (Apache-2.0), instantiated at one
/// static style and subset to the 22 glyphs below — an asset, not an icon
/// package, so it does not breach the built-in-icons-only rule. Flutter's own
/// `Icons` stay the source for everything that is not weather.
///
/// The mapping from a CWB weather code to one of these lives in
/// `weather_condition.dart`.
library;

import 'package:flutter/widgets.dart';

/// The family declared in `pubspec.yaml`.
const String weatherIconFont = 'DpipWeatherIcons';

/// Clear sky by day — a plain sun.
/// Material Symbols `clear_day`.
const IconData clearDay = IconData(0xf157, fontFamily: weatherIconFont);

/// Clear sky by night — a plain moon.
/// Material Symbols `clear_night`.
const IconData clearNight = IconData(0xf159, fontFamily: weatherIconFont);

/// Sun behind a cloud (多雲, day).
/// Material Symbols `partly_cloudy_day`.
const IconData partlyCloudyDay = IconData(0xf172, fontFamily: weatherIconFont);

/// Moon behind a cloud (多雲, night).
/// Material Symbols `partly_cloudy_night`.
const IconData partlyCloudyNight = IconData(
  0xf174,
  fontFamily: weatherIconFont,
);

/// Full cloud cover, no sun or moon (陰).
/// Material Symbols `cloudy`.
const IconData cloudy = IconData(0xf15c, fontFamily: weatherIconFont);

/// Haze / light mist — horizontal streaks, no cloud.
/// Material Symbols `mist`.
const IconData mist = IconData(0xe188, fontFamily: weatherIconFont);

/// A fog bank — denser than mist, drawn with a cloud.
/// Material Symbols `foggy`.
const IconData foggy = IconData(0xe818, fontFamily: weatherIconFont);

/// Light rain or a passing shower.
/// Material Symbols `rainy_light`.
const IconData rainyLight = IconData(0xf61e, fontFamily: weatherIconFont);

/// Steady rain — the everyday Taiwan glyph.
/// Material Symbols `rainy`.
const IconData rainy = IconData(0xf176, fontFamily: weatherIconFont);

/// Torrential rain.
/// Material Symbols `rainy_heavy`.
const IconData rainyHeavy = IconData(0xf61f, fontFamily: weatherIconFont);

/// Rain and snow falling together (雨雪).
/// Material Symbols `rainy_snow`.
const IconData rainySnow = IconData(0xf61d, fontFamily: weatherIconFont);

/// Mixed showers — rain and snow, intermittent.
/// Material Symbols `weather_mix`.
const IconData weatherMix = IconData(0xf60b, fontFamily: weatherIconFont);

/// Snow.
/// Material Symbols `snowing`.
const IconData snowing = IconData(0xe80f, fontFamily: weatherIconFont);

/// Heavy snow.
/// Material Symbols `snowing_heavy`.
const IconData snowingHeavy = IconData(0xf61c, fontFamily: weatherIconFont);

/// Snow grains / graupel.
/// Material Symbols `weather_snowy`.
const IconData weatherSnowy = IconData(0xe2cd, fontFamily: weatherIconFont);

/// Ice pellets — bare crystals, no cloud.
/// Material Symbols `snowflake`.
const IconData snowflake = IconData(0xed5b, fontFamily: weatherIconFont);

/// Hail.
/// Material Symbols `weather_hail`.
const IconData weatherHail = IconData(0xf67f, fontFamily: weatherIconFont);

/// Snow from a storm cloud (雷雪).
/// Material Symbols `cloudy_snowing`.
const IconData cloudySnowing = IconData(0xe810, fontFamily: weatherIconFont);

/// Lightning or thunder with no precipitation.
/// Material Symbols `bolt`.
const IconData bolt = IconData(0xea0b, fontFamily: weatherIconFont);

/// Thunderstorm — rain and lightning.
/// Material Symbols `thunderstorm`.
const IconData thunderstorm = IconData(0xebdb, fontFamily: weatherIconFont);

/// A cyclonic storm.
/// Material Symbols `storm`.
const IconData storm = IconData(0xf070, fontFamily: weatherIconFont);

/// Wind or blowing dust.
/// Material Symbols `air`.
const IconData air = IconData(0xefd8, fontFamily: weatherIconFont);

/// Every glyph in the font, for the coverage test.
const Map<String, IconData> weatherIconsByName = {
  'clear_day': clearDay,
  'clear_night': clearNight,
  'partly_cloudy_day': partlyCloudyDay,
  'partly_cloudy_night': partlyCloudyNight,
  'cloudy': cloudy,
  'mist': mist,
  'foggy': foggy,
  'rainy_light': rainyLight,
  'rainy': rainy,
  'rainy_heavy': rainyHeavy,
  'rainy_snow': rainySnow,
  'weather_mix': weatherMix,
  'snowing': snowing,
  'snowing_heavy': snowingHeavy,
  'weather_snowy': weatherSnowy,
  'snowflake': snowflake,
  'weather_hail': weatherHail,
  'cloudy_snowing': cloudySnowing,
  'bolt': bolt,
  'thunderstorm': thunderstorm,
  'storm': storm,
  'air': air,
};
