// Version-highlight card content for DPIP 26.1 (advanced).
//
// GENERATED from `release_highlights/assets/26.1/advanced/cards.json` by `tool/json_to_dart_highlights.py` — edit the
// JSON, not this file. Rendering lives in `lib/features/release_highlights`;
// this package carries only data.
library;

const title = {
  "zh_Hant": "深入瞭解更多 — 底層真的怎麼運作",
  "zh_Hans": "深入了解详情 — 底层真的怎么运作",
  "en": "Go deeper — how the internals actually work",
  "ja": "さらに詳しく — 内部は実際どう動いているか",
  "ko": "더 자세히 — 내부는 실제로 어떻게 동작하나",
  "th": "เจาะลึก — ระบบภายในทำงานอย่างไรจริง ๆ",
  "vi": "Đi sâu hơn — các phần bên trong thực sự hoạt động ra sao",
  "id": "Lebih dalam — bagaimana sistem internal benar-benar bekerja",
  "fil": "Mas malalim — paano talaga gumagana ang mga internal",
};
const subtitle = {
  "zh_Hant": "給進階使用者與開發者的技術筆記。每一項都來自真實程式碼,附檔案與行號。",
  "zh_Hans": "给进阶使用者与开发者的技术笔记。每一项都来自真实程式码,附档案与行号。",
  "en": "Technical notes for advanced users and developers. Every item traces to real code, with file and line references.",
  "ja": "上級ユーザーと開発者のための技術ノート。すべて実コードに由来し、ファイルと行番号を添えています。",
  "ko": "고급 사용자와 개발자를 위한 기술 노트. 각 항목은 실제 코드에서 나온 것이며, 파일과 줄번호를 포함합니다.",
  "th": "บันทึกเทคนิคสำหรับผู้ใช้ขั้นสูงและนักพัฒนา ทุกรายการมาจากโค้ดจริง พร้อมไฟล์และบรรทัดอ้างอิง",
  "vi": "Ghi chú kỹ thuật cho người dùng nâng cao và lập trình viên. Mỗi mục đều bắt nguồn từ code thật, kèm file và dòng tham chiếu.",
  "id": "Catatan teknis untuk pengguna mahir dan developer. Setiap item berasal dari kode nyata, dengan referensi file dan baris.",
  "fil": "Teknikal na tala para sa mga advanced user at developer. Bawat item ay mula sa tunay na code, may file at line reference.",
};
const cards = <Map<String, dynamic>>[
  {
    'id': "etag_core",
    'icon': "verified",
    'title': {
      "zh_Hant": "ETag SQLite 快取 — 本版最重要的單一改進",
      "zh_Hans": "ETag SQLite 快取 — 本版最重要的单一改进",
      "en": "ETag SQLite cache — the single most important change",
      "ja": "ETag SQLite キャッシュ — 本バージョン最重要の変更",
      "ko": "ETag SQLite 캐시 — 이번 버전의 가장 중요한 변화",
      "th": "แคช ETag SQLite — การเปลี่ยนแปลงที่สำคัญที่สุดในเวอร์ชันนี้",
      "vi": "Cache ETag SQLite — thay đổi quan trọng nhất của bản này",
      "id": "Cache ETag SQLite — perubahan terpenting versi ini",
      "fil": "ETag SQLite cache — ang pinakamahalagang pagbabago",
    },
    'headline': null,
    'body': {
      "zh_Hant": "全新網址為鍵、ETag 驗證、LRU 位元組預算的 SQLite HTTP 快取。檔案:`core/network/etag_interceptor.dart` + `etag_cache_store.dart`。",
      "zh_Hans": "全新网址为键、ETag 验证、LRU 位元组预算的 SQLite HTTP 快取。档案:core/network/etag_interceptor.dart + etag_cache_store.dart。",
      "en": "A URL-keyed, ETag-validated, LRU byte-budgeted SQLite HTTP cache. Files: core/network/etag_interceptor.dart + etag_cache_store.dart.",
      "ja": "URL キー、ETag 検証、LRU バイト予算の SQLite キャッシュ。ファイル: core/network/etag_interceptor.dart + etag_cache_store.dart。",
      "ko": "URL 키, ETag 검증, LRU 바이트 예산 SQLite HTTP 캐시. 파일: core/network/etag_interceptor.dart + etag_cache_store.dart.",
      "th": "แคช SQLite แบบใช้ URL เป็นคีย์ ตรวจสอบ ETag และจัดงบประมาณแบบ LRU ไฟล์: core/network/etag_interceptor.dart + etag_cache_store.dart",
      "vi": "Cache HTTP SQLite theo khóa URL, xác thực ETag, ngân sách byte LRU. File: core/network/etag_interceptor.dart + etag_cache_store.dart.",
      "id": "Cache HTTP SQLite berbasis kunci URL, validasi ETag, anggaran byte LRU. File: core/network/etag_interceptor.dart + etag_cache_store.dart.",
      "fil": "URL-keyed, ETag-validated, LRU byte-budget SQLite HTTP cache. Files: core/network/etag_interceptor.dart + etag_cache_store.dart.",
    },
    'stat': null,
    'statLabel': null,
    'highlights': <Map<String, String>>[],
    'details': <Map<String, dynamic>>[
      {
        'key': {
          "zh_Hant": "驗證方式",
          "zh_Hans": "验证方式",
          "en": "Validation",
          "ja": "検証方式",
          "ko": "검증 방식",
          "th": "การตรวจสอบ",
          "vi": "Xác thực",
          "id": "Validasi",
          "fil": "Validation",
        },
        'value': {
          "zh_Hant":
              "ETag 是唯一 validator;Cache-Control / no-store 被忽略;200 無 ETag 不寫入",
          "zh_Hans":
              "ETag 是唯一 validator;Cache-Control / no-store 被忽略;200 无 ETag 不写入",
          "en": "ETag is the sole validator; Cache-Control/no-store ignored; 200s without an ETag are not cached",
          "ja": "ETag が唯一のバリデータ。Cache-Control/no-store は無視。ETag なしの 200 はキャッシュしない",
          "ko": "ETag이 유일한 검증자. Cache-Control/no-store 무시. ETag 없는 200은 캐시 안 함",
          "th": "ETag เป็นตัวตรวจสอบเดียว; ไม่สนใจ Cache-Control/no-store; 200 ที่ไม่มี ETag จะไม่ถูกแคช",
          "vi": "ETag là validator duy nhất; Cache-Control/no-store bị bỏ qua; 200 không có ETag không được lưu",
          "id": "ETag satu-satunya validator; Cache-Control/no-store diabaikan; 200 tanpa ETag tidak dicache",
          "fil": "ETag lang ang validator; hindi pinapansin ang Cache-Control/no-store; hindi naka-cache ang 200 na walang ETag",
        },
      },
      {
        'key': {
          "zh_Hant": "過期模型",
          "zh_Hans": "过期模型",
          "en": "Expiry model",
          "ja": "有効期限モデル",
          "ko": "만료 모델",
          "th": "โมเดลการหมดอายุ",
          "vi": "Mô hình hết hạn",
          "id": "Model kedaluwarsa",
          "fil": "Expiry model",
        },
        'value': {
          "zh_Hant": "不按時間;只有位元組預算(350 MiB)。30 天前仍被 hit 的 tile 保留位置",
          "zh_Hans": "不按时间;只有位元组预算(350 MiB)。30 天前仍被 hit 的 tile 保留位置",
          "en": "Not time-based; only a byte budget (350 MiB). A tile still being hit after 30 days keeps its place",
          "ja": "時間ベースではない。バイト予算のみ (350 MiB)。30 日後もヒット中のタイルは場所を維持",
          "ko": "시간 기반이 아님. 오직 바이트 예산(350MiB). 30일 지나도 계속 hit되는 타일은 유지",
          "th": "ไม่อิงเวลา มีแค่งบประมาณไบต์ (350 MiB) ไทล์ที่ยังถูกเรียกใช้หลัง 30 วันยังคงอยู่",
          "vi": "Không theo thời gian; chỉ có ngân sách byte (350 MiB). Tile vẫn được gọi sau 30 ngày giữ nguyên vị trí",
          "id": "Tidak berbasis waktu; hanya anggaran byte (350 MiB). Tile yang masih diakses setelah 30 hari tetap bertahan",
          "fil": "Hindi time-based; byte budget lang (350 MiB). Nananatili ang tile na ginagamit pa rin kahit 30 araw",
        },
      },
      {
        'key': {
          "zh_Hant": "高變動資料",
          "zh_Hans": "高变动资料",
          "en": "Volatile data",
          "ja": "高変動データ",
          "ko": "고변동 데이터",
          "th": "ข้อมูลที่เปลี่ยนแปลงบ่อย",
          "vi": "Dữ liệu biến động cao",
          "id": "Data berubah cepat",
          "fil": "Madaling magbago na data",
        },
        'value': {
          "zh_Hant": "EEW、RTS、location、notify 永不快取——token 不落磁碟",
          "zh_Hans": "EEW、RTS、location、notify 永不快取——token 不落磁盘",
          "en": "EEW, RTS, location and notify are never cached — tokens never touch disk",
          "ja": "EEW・RTS・location・notify は絶対にキャッシュしない。トークンはディスクに落ちない",
          "ko": "EEW, RTS, location, notify는 절대 캐시 안 함 — 토큰은 디스크에 안 닿음",
          "th": "EEW, RTS, location, notify ไม่ถูกแคชเด็ดขาด — token ไม่ถูกเขียนลงดิสก์",
          "vi": "EEW, RTS, location, notify không bao giờ bị cache — token không chạm đĩa",
          "id": "EEW, RTS, location, notify tidak pernah dicache — token tidak menyentuh disk",
          "fil": "EEW, RTS, location, notify — hindi kailanman naka-cache; hindi nahahawakan ng disk ang token",
        },
      },
      {
        'key': {
          "zh_Hant": "不可變資產",
          "zh_Hans": "不可变资产",
          "en": "Immutable assets",
          "ja": "不変アセット",
          "ko": "불변 에셋",
          "th": "ทรัพยากรที่ไม่เปลี่ยนแปลง",
          "vi": "Tài sản bất biến",
          "id": "Aset tidak berubah",
          "fil": "Immutable assets",
        },
        'value': {
          "zh_Hant": "URL 就 pin 住內容:本地 hit 直接 serve,永不發 If-None-Match",
          "zh_Hans": "URL 就 pin 住内容:本地 hit 直接 serve,永不发 If-None-Match",
          "en": "The URL pins the content: local hits serve directly, If-None-Match is never sent",
          "ja": "URL が内容を固定する。ローカルヒットは直接サーブし、If-None-Match は送らない",
          "ko": "URL이 내용을 고정. 로컬 히트는 바로 서브, If-None-Match는 절대 안 보냄",
          "th": "URL ยึดเนื้อหาไว้: ฮิตในเครื่องเซิร์ฟโดยตรง ไม่ส่ง If-None-Match เลย",
          "vi": "URL cố định nội dung: hit cục bộ phục vụ trực tiếp, không bao giờ gửi If-None-Match",
          "id": "URL mengunci konten: hit lokal langsung disajikan, If-None-Match tidak pernah dikirim",
          "fil": "Ang URL ang nagla-lock ng content: direktang sineserve ang local hit, hindi na ipinapadala ang If-None-Match",
        },
      },
      {
        'key': {
          "zh_Hant": "304 處理",
          "zh_Hans": "304 处理",
          "en": "304 handling",
          "ja": "304 の扱い",
          "ko": "304 처리",
          "th": "การจัดการ 304",
          "vi": "Xử lý 304",
          "id": "Penanganan 304",
          "fil": "Paghawak ng 304",
        },
        'value': {
          "zh_Hant": "空 304 被改寫回帶 cached body 的 200,呼叫者看不到 304",
          "zh_Hans": "空 304 被改写回带 cached body 的 200,呼叫者看不到 304",
          "en": "An empty 304 is rewritten as a 200 with the cached body — callers never see 304",
          "ja": "空の 304 はキャッシュボディ付き 200 に書き換えられ、呼び出し元は 304 を見ない",
          "ko": "빈 304는 캐시된 body가 있는 200으로 다시 쓰여져, 호출자는 304를 못 봄",
          "th": "304 เปล่าแปลงกลับเป็น 200 พร้อม body แคช ผู้เรียกไม่เห็น 304",
          "vi": "304 rỗng được viết lại thành 200 kèm body đã cache — caller không bao giờ thấy 304",
          "id": "304 kosong ditulis ulang sebagai 200 dengan body cache — pemanggil tidak pernah melihat 304",
          "fil": "Ang walang laman na 304 ay ginagawang 200 na may cached body — hindi nakikita ng caller ang 304",
        },
      },
      {
        'key': {
          "zh_Hant": "儲存工程",
          "zh_Hans": "储存工程",
          "en": "Storage engineering",
          "ja": "ストレージ設計",
          "ko": "저장 엔지니어링",
          "th": "วิศวกรรมพื้นที่จัดเก็บ",
          "vi": "Kỹ thuật lưu trữ",
          "id": "Teknik penyimpanan",
          "fil": "Storage engineering",
        },
        'value': {
          "zh_Hant": "WAL + PRAGMA cache_size -25600 (25 MiB page cache) + mmap 64 MiB;批次讀寫;JSON gzip-1(壓不縮就存 raw)",
          "zh_Hans": "WAL + PRAGMA cache_size -25600 (25 MiB page cache) + mmap 64 MiB;批次读写;JSON gzip-1(压不缩就存 raw)",
          "en": "WAL + PRAGMA cache_size -25600 (25 MiB page cache) + mmap 64 MiB; batched reads/writes; JSON gzip-1 (stored raw when it does not compress)",
          "ja": "WAL + PRAGMA cache_size -25600 (25 MiB ページキャッシュ) + mmap 64 MiB。バッチ読み書き。JSON は gzip-1(圧縮効果がなければ raw で保存)",
          "ko": "WAL + PRAGMA cache_size -25600 (25MiB 페이지 캐시) + mmap 64MiB. 배치 읽기/쓰기. JSON gzip-1 (압축 안 되면 raw로 저장)",
          "th": "WAL + PRAGMA cache_size -25600 (page cache 25 MiB) + mmap 64 MiB; อ่านเขียนแบบแบตช์; JSON gzip-1 (เก็บแบบ raw ถ้าบีบไม่ลง)",
          "vi": "WAL + PRAGMA cache_size -25600 (25 MiB page cache) + mmap 64 MiB; đọc/ghi theo lô; JSON gzip-1 (giữ raw nếu không nén được)",
          "id": "WAL + PRAGMA cache_size -25600 (cache halaman 25 MiB) + mmap 64 MiB; baca/tulis batch; JSON gzip-1 (disimpan raw jika tidak terkompresi)",
          "fil": "WAL + PRAGMA cache_size -25600 (25 MiB page cache) + mmap 64 MiB; batched read/write; JSON gzip-1 (raw ang itatago kung hindi mag-compress)",
        },
      },
    ],
    'stats': <Map<String, dynamic>>[],
  },
  {
    'id': "region_failover",
    'icon': "route",
    'title': {
      "zh_Hant": "區域選路與多活自動故障轉移",
      "zh_Hans": "区域选路与多活自动故障转移",
      "en": "Region routing and multi-active failover",
      "ja": "リージョン選定とマルチアクティブ・フェイルオーバー",
      "ko": "리전 라우팅과 다중 활성 장애 조치",
      "th": "การเลือกภูมิภาคและการสลับเซิร์ฟเวอร์อัตโนมัติ",
      "vi": "Định tuyến vùng và chuyển đổi dự phòng đa chủ động",
      "id": "Routing wilayah dan failover multi-aktif",
      "fil": "Region routing at multi-active failover",
    },
    'headline': null,
    'body': {
      "zh_Hant": "決定權從 DNS 平衡移到 app 內(app 自己 pin 住 region host),失敗時依序換下一台。檔案:`core/network/api_region.dart` + `region_selection.dart`。",
      "zh_Hans": "决定权从 DNS 平衡移到 app 内(app 自己 pin 住 region host),失败时依序换下一台。档案:core/network/api_region.dart + region_selection.dart。",
      "en": "Selection authority moved from DNS load balancing into the app (which pins region hosts itself), failing over to the next host in order. Files: core/network/api_region.dart + region_selection.dart.",
      "ja": "選定の主導権が DNS ロードバランサーからアプリ内(自らリージョンホストを固定)へ。失敗時は次のホストへ順に切り替え。ファイル: core/network/api_region.dart + region_selection.dart。",
      "ko": "선택 권한이 DNS 로드밸런싱에서 앱 내부(리전 호스트를 직접 고정)로 이동. 실패 시 다음 호스트로 순서대로 전환. 파일: core/network/api_region.dart + region_selection.dart.",
      "th": "อำนาจการเลือกย้ายจาก DNS load balancing มาในแอป (ซึ่งปัก host ภูมิภาคเอง) และสลับไปยัง host ถัดไปเมื่อล้มเหลว ไฟล์: core/network/api_region.dart + region_selection.dart",
      "vi": "Quyền chọn lựa chuyển từ cân bằng tải DNS vào trong app (tự ghim host vùng), chuyển sang host kế tiếp khi lỗi. File: core/network/api_region.dart + region_selection.dart.",
      "id": "Kewenangan pemilihan pindah dari load balancing DNS ke dalam app (yang men-pin host region sendiri), gagal lalu beralih ke host berikutnya. File: core/network/api_region.dart + region_selection.dart.",
      "fil": "Ang awtoridad sa pagpili ay lumipat mula sa DNS load balancing papasok sa app (na siya mismo ang nagpi-pin ng region host), nag-failover sa susunod na host. Files: core/network/api_region.dart + region_selection.dart.",
    },
    'stat': null,
    'statLabel': null,
    'highlights': <Map<String, String>>[],
    'details': <Map<String, dynamic>>[
      {
        'key': {
          "zh_Hant": "7 個 tier",
          "zh_Hans": "7 个 tier",
          "en": "7 tiers",
          "ja": "7 つのティア",
          "ko": "7개 티어",
          "th": "7 ระดับ",
          "vi": "7 tầng",
          "id": "7 tier",
          "fil": "7 tier",
        },
        'value': {
          "zh_Hant": "4 個 region 的 concrete host;從不請求 DNS 平衡的裸 host;選中的 region 被 persisted",
          "zh_Hans": "4 个 region 的 concrete host;从不请求 DNS 平衡的裸 host;选中的 region 被 persisted",
          "en": "Concrete hosts across 4 regions; never hits a bare DNS-balanced host; the chosen region is persisted",
          "ja": "4 リージョンの concrete host。DNS 分散の素のホストには決して接続しない。選択リージョンは永続化",
          "ko": "4개 리전의 구체적 호스트. DNS 밸런싱된 호스트는 절대 안 씀. 선택한 리전은 영구 저장",
          "th": "โฮสต์จริงใน 4 ภูมิภาค ไม่เคยเรียกใช้ host ที่ใช้ DNS balancing; ภูมิภาคที่เลือกถูกบันทึกถาวร",
          "vi": "Host cụ thể trên 4 vùng; không bao giờ gọi host DNS cân bằng; vùng đã chọn được lưu bền vững",
          "id": "Host konkret di 4 region; tidak pernah memanggil host balancing DNS; region terpilih dipersist",
          "fil": "Mga konkretong host sa 4 na region; hindi kailanman gumagamit ng bare DNS-balance host; naka-persist ang napiling region",
        },
      },
      {
        'key': {
          "zh_Hant": "Failover 條件",
          "zh_Hans": "Failover 条件",
          "en": "Failover rules",
          "ja": "フェイルオーバー条件",
          "ko": "장애 조치 조건",
          "th": "เงื่อนไขการสลับ",
          "vi": "Điều kiện failover",
          "id": "Aturan failover",
          "fil": "Failover rules",
        },
        'value': {
          "zh_Hant":
              "只有 connection / timeout / 5xx 換台;4xx 和 user cancel 直接 throw",
          "zh_Hans":
              "只有 connection / timeout / 5xx 换台;4xx 和 user cancel 直接 throw",
          "en": "Only connection/timeout/5xx trigger a switch; 4xx and user cancellation throw directly",
          "ja": "接続・タイムアウト・5xx のみ切り替える。4xx とユーザーキャンセルは直接 throw",
          "ko": "연결/타임아웃/5xx만 전환. 4xx와 사용자 취소는 그냥 throw",
          "th": "เฉพาะ connection/timeout/5xx ที่สลับ; 4xx และการยกเลิกโดยผู้ใช้ throw โดยตรง",
          "vi": "Chỉ connection/timeout/5xx mới chuyển; 4xx và huỷ do người dùng throw thẳng",
          "id": "Hanya connection/timeout/5xx yang memicu pindah; 4xx dan cancel user langsung throw",
          "fil": "Connection/timeout/5xx lang ang nagpapalit; ang 4xx at cancellation ay nag-throw na lang",
        },
      },
      {
        'key': {
          "zh_Hant": "Timeout 策略",
          "zh_Hans": "Timeout 策略",
          "en": "Timeout strategy",
          "ja": "タイムアウト戦略",
          "ko": "타임아웃 전략",
          "th": "กลยุทธ์ timeout",
          "vi": "Chiến lược timeout",
          "id": "Strategi timeout",
          "fil": "Timeout strategy",
        },
        'value': {
          "zh_Hant": "connectTimeout 8s / receiveTimeout 10s:快點死、快點 failover",
          "zh_Hans": "connectTimeout 8s / receiveTimeout 10s:快点死、快点 failover",
          "en": "connectTimeout 8s / receiveTimeout 10s — fail fast, fail over fast",
          "ja": "connectTimeout 8s / receiveTimeout 10s — 早く死に、早くフェイルオーバー",
          "ko": "connectTimeout 8s / receiveTimeout 10s — 빨리 죽고 빨리 전환",
          "th": "connectTimeout 8s / receiveTimeout 10s — ตายเร็ว สลับเร็ว",
          "vi": "connectTimeout 8s / receiveTimeout 10s — chết nhanh, failover nhanh",
          "id": "connectTimeout 8s / receiveTimeout 10s — cepat gagal, cepat failover",
          "fil": "connectTimeout 8s / receiveTimeout 10s — mamatay nang mabilis, lumipat nang mabilis",
        },
      },
      {
        'key': {
          "zh_Hant": "健康觀測",
          "zh_Hans": "健康观测",
          "en": "Health monitoring",
          "ja": "健全性モニタリング",
          "ko": "건강 모니터링",
          "th": "การเฝ้าระวังสุขภาพระบบ",
          "vi": "Giám sát sức khỏe",
          "id": "Pemantauan kesehatan",
          "fil": "Health monitoring",
        },
        'value': {
          "zh_Hant":
              "service × tier × host 分桶;連續失敗 ≥2 次才判 down;4xx/cancel/cert 不計入",
          "zh_Hans":
              "service × tier × host 分桶;连续失败 ≥2 次才判 down;4xx/cancel/cert 不计入",
          "en": "Bucketed by service × tier × host; ≥2 consecutive failures mark down; 4xx/cancel/cert errors don't count",
          "ja": "service × tier × host でバケット化。2 回以上連続失敗で down。4xx・キャンセル・証明書エラーは数えない",
          "ko": "service × tier × host 버킷. 2회 이상 연속 실패 시 down. 4xx/취소/인증서 오류는 미집계",
          "th": "แบ่งกลุ่มตาม service × tier × host; ล้มเหลวติดต่อกัน ≥2 ครั้งถึงจะลงว่า down; 4xx/cancel/cert ไม่นับ",
          "vi": "Phân nhóm theo service × tier × host; ≥2 lần lỗi liên tiếp mới là down; 4xx/cancel/cert không tính",
          "id": "Dikelompokkan per service × tier × host; gagal berturut-turut ≥2 kali baru down; 4xx/cancel/cert tidak dihitung",
          "fil": "Naka-bucket sa service × tier × host; ≥2 sunod-sunod na palya ang sasabihing down; hindi binibilang ang 4xx/cancel/cert",
        },
      },
    ],
    'stats': <Map<String, dynamic>>[],
  },
  {
    'id': "sse_stream",
    'icon': "stream",
    'title': {
      "zh_Hant": "SSE 串流取代每秒輪詢",
      "zh_Hans": "SSE 串流取代每秒轮询",
      "en": "SSE streaming replaces second-by-second polling",
      "ja": "SSE ストリームが毎秒ポーリングに取って代わる",
      "ko": "SSE 스트리밍이 초당 폴링을 대체",
      "th": "SSE streaming แทนที่การดึงข้อมูลทุกวินาที",
      "vi": "SSE streaming thay thế kéo dữ liệu mỗi giây",
      "id": "SSE streaming menggantikan polling per detik",
      "fil": "Pinapalitan ng SSE streaming ang polling bawat segundo",
    },
    'headline': null,
    'body': {
      "zh_Hant": "核心即時資料傳輸改以 Server-Sent Events 串流。檔案:`core/network/sse_client.dart` + `core/realtime/sse_realtime_source.dart`。",
      "zh_Hans": "核心即时资料传输改以 Server-Sent Events 串流。档案:core/network/sse_client.dart + core/realtime/sse_realtime_source.dart。",
      "en": "Core real-time data moves over Server-Sent Events streaming. Files: core/network/sse_client.dart + core/realtime/sse_realtime_source.dart.",
      "ja": "中核のリアルタイムデータ転送が Server-Sent Events ストリーミングに移行。ファイル: core/network/sse_client.dart + core/realtime/sse_realtime_source.dart。",
      "ko": "핵심 실시간 데이터 전송이 SSE 스트리밍으로 전환. 파일: core/network/sse_client.dart + core/realtime/sse_realtime_source.dart.",
      "th": "ข้อมูลเรียลไทม์หลักเปลี่ยนเป็นการส่งแบบ Server-Sent Events ไฟล์: core/network/sse_client.dart + core/realtime/sse_realtime_source.dart",
      "vi": "Dữ liệu thời gian thực cốt lõi chuyển sang streaming Server-Sent Events. File: core/network/sse_client.dart + core/realtime/sse_realtime_source.dart.",
      "id": "Transfer data real-time inti beralih ke streaming Server-Sent Events. File: core/network/sse_client.dart + core/realtime/sse_realtime_source.dart.",
      "fil": "Ang core real-time data ay nasa Server-Sent Events streaming na. Files: core/network/sse_client.dart + core/realtime/sse_realtime_source.dart.",
    },
    'stat': null,
    'statLabel': null,
    'highlights': <Map<String, String>>[],
    'details': <Map<String, dynamic>>[
      {
        'key': {
          "zh_Hant": "壓縮事件",
          "zh_Hans": "压缩事件",
          "en": "Compressed events",
          "ja": "圧縮イベント",
          "ko": "압축 이벤트",
          "th": "เหตุการณ์บีบอัด",
          "vi": "Sự kiện nén",
          "id": "Event terkompresi",
          "fil": "Compressed events",
        },
        'value': {
          "zh_Hant": "event: g 事件,data: 是 base64 gzip;資料格式與純 GET 相同,模型不變",
          "zh_Hans": "event: g 事件,data: 是 base64 gzip;资料格式与纯 GET 相同,模型不变",
          "en": "event: g events carry base64 gzip data; the payload is identical to the plain GET, so the model never changes",
          "ja": "event: g イベントの data は base64 gzip。ペイロードは素の GET と同一で、モデルは変わらない",
          "ko": "event: g 이벤트, data는 base64 gzip. 페이로드는 일반 GET과 동일해서 모델은 그대로",
          "th": "เหตุการณ์ event: g, data เป็น base64 gzip; รูปแบบข้อมูลเหมือน GET ทั่วไป รุ่นไม่เปลี่ยน",
          "vi": "Sự kiện event: g, data là base64 gzip; payload giống hệt GET thuần, model không đổi",
          "id": "Event event: g, data berbentuk base64 gzip; payload sama persis dengan GET biasa, model tak berubah",
          "fil": "Ang event: g, data ay base64 gzip; kapareho ng plain GET ang payload, hindi nagbabago ang model",
        },
      },
      {
        'key': {
          "zh_Hant": "Backoff",
          "zh_Hans": "Backoff",
          "en": "Backoff",
          "ja": "バックオフ",
          "ko": "백오프",
          "th": "การถอยหลัง",
          "vi": "Backoff",
          "id": "Backoff",
          "fil": "Backoff",
        },
        'value': {
          "zh_Hant": "1s → 2s → cap 在 server retry hint(預設 3s);事件一到立刻歸零",
          "zh_Hans": "1s → 2s → cap 在 server retry hint(预设 3s);事件一到立刻归零",
          "en": "1s → 2s, capped at the server retry hint (3s default); zeroed instantly on any event",
          "ja": "1s → 2s → server の retry ヒント(デフォルト 3s)で上限。イベント到着で即リセット",
          "ko": "1s → 2s → 서버 retry 힌트(기본 3s)에서 제한. 이벤트 오면 즉시 초기화",
          "th": "1s → 2s → จำกัดที่ค่า retry จากเซิร์ฟเวอร์ (ค่าเริ่มต้น 3s); รีเซ็ตทันทีเมื่อมีเหตุการณ์",
          "vi": "1s → 2s, chặn ở hint retry của server (mặc định 3s); về 0 ngay khi có sự kiện",
          "id": "1s → 2s, di-cap pada hint retry server (default 3s); seketika nol saat ada event",
          "fil": "1s → 2s, may cap sa server retry hint (default 3s); babalik sa zero pagdating ng event",
        },
      },
      {
        'key': {
          "zh_Hant": "兩種 liveness",
          "zh_Hans": "两种 liveness",
          "en": "Two liveness modes",
          "ja": "2 種類の liveness",
          "ko": "두 가지 라이브니스",
          "th": "โหมด liveness สองแบบ",
          "vi": "Hai chế độ liveness",
          "id": "Dua mode liveness",
          "fil": "Dalawang liveness mode",
        },
        'value': {
          "zh_Hant":
              "EEW 用 connectionOpen(地震之間無聲);RTS 用 eventRecency 3s 窗(連續 feed)",
          "zh_Hans":
              "EEW 用 connectionOpen(地震之间无声);RTS 用 eventRecency 3s 窗(连续 feed)",
          "en": "EEW uses connectionOpen (silent between quakes); RTS uses a 3s event-recency window (continuous feed)",
          "ja":
              "EEW は connectionOpen(地震間は無音)、RTS は 3 秒の eventRecency 窓(連続フィード)",
          "ko":
              "EEW는 connectionOpen(지진 사이엔 침묵), RTS는 3초 eventRecency 윈도(연속 피드)",
          "th": "EEW ใช้ connectionOpen (เงียบระหว่างแผ่นดินไหว); RTS ใช้ eventRecency 3 วินาที (feed ต่อเนื่อง)",
          "vi": "EEW dùng connectionOpen (im lặng giữa các trận động đất); RTS dùng cửa sổ eventRecency 3s (feed liên tục)",
          "id": "EEW pakai connectionOpen (hening di antara gempa); RTS pakai jendela eventRecency 3 detik (feed kontinu)",
          "fil": "EEW gumagamit ng connectionOpen (tahimik sa pagitan ng lindol); RTS gumagamit ng 3s eventRecency window (continuous feed)",
        },
      },
      {
        'key': {
          "zh_Hant": "Push → poll 橋",
          "zh_Hans": "Push → poll 桥",
          "en": "Push → poll bridge",
          "ja": "Push → poll ブリッジ",
          "ko": "Push → poll 브리지",
          "th": "สะพาน Push → poll",
          "vi": "Cầu nối Push → poll",
          "id": "Jembatan Push → poll",
          "fil": "Push → poll bridge",
        },
        'value': {
          "zh_Hant":
              "fetch() 回傳緩衝的最新 snapshot 當成當前狀態;整個 live→stale→offline 骨架重用",
          "zh_Hans":
              "fetch() 回传缓冲的最新 snapshot 当成当前状态;整个 live→stale→offline 骨架重用",
          "en": "fetch() returns the latest buffered snapshot as the current state; the whole live→stale→offline skeleton is reused",
          "ja": "fetch() はバッファ済み最新スナップショットを現在状態として返す。live→stale→offline の骨格はすべて再利用",
          "ko": "fetch()는 버퍼링된 최신 스냅샷을 현재 상태로 반환. live→stale→offline 골격 전체 재사용",
          "th": "fetch() คืนสแนปช็อตล่าสุดที่บัฟเฟอร์เป็นสถานะปัจจุบัน; โครง live→stale→offline ทั้งหมดถูกใช้ซ้ำ",
          "vi": "fetch() trả về snapshot mới nhất đã đệm như trạng thái hiện tại; toàn bộ khung live→stale→offline được tái sử dụng",
          "id": "fetch() mengembalikan snapshot terbaru yang di-buffer sebagai status saat ini; seluruh kerangka live→stale→offline dipakai ulang",
          "fil": "Ibinabalik ng fetch() ang pinakabagong buffered snapshot bilang kasalukuyang estado; ginamit muli ang buong live→stale→offline skeleton",
        },
      },
    ],
    'stats': <Map<String, dynamic>>[],
  },
  {
    'id': "dual_db",
    'icon': "storage",
    'title': {
      "zh_Hant": "雙 SQLite:按耐久性切分",
      "zh_Hans": "双 SQLite:按耐久性切分",
      "en": "Two SQLite files: split by durability",
      "ja": "二つの SQLite:耐久性で分割",
      "ko": "SQLite 2개: 내구성 기준 분리",
      "th": "SQLite สองไฟล์: แบ่งตามความคงทน",
      "vi": "Hai SQLite: chia theo độ bền",
      "id": "Dua SQLite: dipisah berdasarkan ketahanan",
      "fil": "Dalawang SQLite: nahati ayon sa tibay",
    },
    'headline': null,
    'body': {
      "zh_Hant": "不再一個檔裝全部。按「資料能不能重抓」決定放哪個資料庫。檔案:`core/storage/app_database.dart` + `core/network/etag_cache_store.dart`。",
      "zh_Hans": "不再一个档装全部。按「资料能不能重抓」决定放哪个资料库。档案:core/storage/app_database.dart + core/network/etag_cache_store.dart。",
      "en": "No more one file for everything. Where data lives is decided by 'can it be re-fetched?'. Files: core/storage/app_database.dart + core/network/etag_cache_store.dart.",
      "ja": "1 ファイルですべてを済ませるのをやめ、データが「再取得できるか」で置き場所を決める。ファイル: core/storage/app_database.dart + core/network/etag_cache_store.dart。",
      "ko": "한 파일에 다 넣던 방식을 버리고, '다시 받을 수 있는지'로 저장 위치를 결정. 파일: core/storage/app_database.dart + core/network/etag_cache_store.dart.",
      "th": "ไม่ใช้ไฟล์เดียวเก็บทุกอย่างอีกต่อไป พิจารณาว่า \"ข้อมูลโหลดใหม่ได้ไหม\" เพื่อเลือกฐานข้อมูล ไฟล์: core/storage/app_database.dart + core/network/etag_cache_store.dart",
      "vi": "Không còn một file chứa mọi thứ. Vị trí dữ liệu do \"có thể tải lại không\" quyết định. File: core/storage/app_database.dart + core/network/etag_cache_store.dart.",
      "id": "Tidak lagi satu file untuk semuanya. Lokasi data ditentukan oleh 'bisa diunduh ulang?'. File: core/storage/app_database.dart + core/network/etag_cache_store.dart.",
      "fil": "Hindi na isang file para sa lahat. Kung saan titira ang data ay pinagpapasyahan ng 'maaari bang kunin muli?'. Files: core/storage/app_database.dart + core/network/etag_cache_store.dart.",
    },
    'stat': null,
    'statLabel': null,
    'highlights': <Map<String, String>>[],
    'details': <Map<String, dynamic>>[
      {
        'key': {
          "zh_Hant": "dpip.db",
          "zh_Hans": "dpip.db",
          "en": "dpip.db",
          "ja": "dpip.db",
          "ko": "dpip.db",
          "th": "dpip.db",
          "vi": "dpip.db",
          "id": "dpip.db",
          "fil": "dpip.db",
        },
        'value': {
          "zh_Hant": "application-support(OS 不可清):settings、logs(24h)、tle、mesh;synchronous = FULL",
          "zh_Hans": "application-support(OS 不可清):settings、logs(24h)、tle、mesh;synchronous = FULL",
          "en": "application-support (OS-uncullable): settings, logs (24h), TLE, mesh; synchronous = FULL",
          "ja": "application-support(OS に消されない): settings、logs (24h)、tle、mesh。synchronous = FULL",
          "ko": "application-support(OS가 못 지움): settings, logs(24h), tle, mesh. synchronous = FULL",
          "th": "application-support (ระบบไม่ลบ): settings, logs (24 ชม.), tle, mesh; synchronous = FULL",
          "vi": "application-support (OS không xoá được): settings, logs (24h), tle, mesh; synchronous = FULL",
          "id": "application-support (tak bisa dihapus OS): settings, logs (24 jam), tle, mesh; synchronous = FULL",
          "fil": "application-support (hindi pwedeng burahin ng OS): settings, logs (24h), tle, mesh; synchronous = FULL",
        },
      },
      {
        'key': {
          "zh_Hant": "http_etag_cache.db",
          "zh_Hans": "http_etag_cache.db",
          "en": "http_etag_cache.db",
          "ja": "http_etag_cache.db",
          "ko": "http_etag_cache.db",
          "th": "http_etag_cache.db",
          "vi": "http_etag_cache.db",
          "id": "http_etag_cache.db",
          "fil": "http_etag_cache.db",
        },
        'value': {
          "zh_Hant": "cache(OS 可清):http_cache、net_bucket;synchronous = NORMAL(WAL commit 零 fsync)",
          "zh_Hans": "cache(OS 可清):http_cache、net_bucket;synchronous = NORMAL(WAL commit 零 fsync)",
          "en": "cache (OS-cullable): http_cache, net_bucket; synchronous = NORMAL (zero-fsync WAL commits)",
          "ja": "cache(OS に消され得る): http_cache、net_bucket。synchronous = NORMAL(WAL commit は fsync なし)",
          "ko": "cache(OS가 지울 수 있음): http_cache, net_bucket. synchronous = NORMAL (WAL commit 무 fsync)",
          "th": "cache (ระบบลบได้): http_cache, net_bucket; synchronous = NORMAL (WAL commit ไม่ fsync)",
          "vi": "cache (OS xoá được): http_cache, net_bucket; synchronous = NORMAL (commit WAL không fsync)",
          "id": "cache (bisa dihapus OS): http_cache, net_bucket; synchronous = NORMAL (commit WAL tanpa fsync)",
          "fil": "cache (pwedeng burahin ng OS): http_cache, net_bucket; synchronous = NORMAL (walang fsync ang WAL commit)",
        },
      },
      {
        'key': {
          "zh_Hant": "WAL 的意義",
          "zh_Hans": "WAL 的意义",
          "en": "Why WAL matters",
          "ja": "WAL の意義",
          "ko": "WAL의 의미",
          "th": "ความสำคัญของ WAL",
          "vi": "Ý nghĩa của WAL",
          "id": "Mengapa WAL penting",
          "fil": "Bakit mahalaga ang WAL",
        },
        'value': {
          "zh_Hant": "每個小 transaction(log flush、LRU touch、tile batch)不再建 journal + fsync 數次;只 append 到長命 -wal 檔",
          "zh_Hans": "每个小 transaction(log flush、LRU touch、tile batch)不再建 journal + fsync 数次;只 append 到长命 -wal 档",
          "en": "Small transactions (log flush, LRU touch, tile batch) no longer create a journal + several fsyncs; they just append to a long-lived -wal file",
          "ja": "小さなトランザクション(log flush、LRU touch、tile batch)はジャーナル作成+複数 fsync をしなくなり、長命の -wal ファイルに追記するだけになる",
          "ko": "작은 트랜잭션(log flush, LRU touch, tile batch)은 더 이상 저널 + fsync 여러 번을 하지 않고, 오래 사는 -wal 파일에 append만 함",
          "th": "ธุรกรรมเล็ก (log flush, LRU touch, tile batch) ไม่สร้าง journal + fsync หลายครั้งอีกแล้ว แค่ append ไปยังไฟล์ -wal ที่มีอายุยาว",
          "vi": "Transaction nhỏ (log flush, LRU touch, tile batch) không còn tạo journal + nhiều lần fsync; chỉ append vào file -wal sống lâu",
          "id": "Transaksi kecil (log flush, LRU touch, tile batch) tidak lagi membuat jurnal + beberapa fsync; cukup append ke file -wal panjang umur",
          "fil": "Ang maliliit na transaksyon (log flush, LRU touch, tile batch) ay hindi na gumagawa ng journal + ilang fsync; nag-a-append lang sa mahabang -wal file",
        },
      },
      {
        'key': {
          "zh_Hant": "保留策略",
          "zh_Hans": "保留策略",
          "en": "Retention",
          "ja": "保持期間",
          "ko": "보존 정책",
          "th": "นโยบายการเก็บรักษา",
          "vi": "Chính sách giữ lại",
          "id": "Kebijakan retensi",
          "fil": "Retention",
        },
        'value': {
          "zh_Hant": "集中 hourly sweep(啟動後 1 分首 sweep):mesh 30 天、radio/neighbour 24h、app log 24h、net_bucket 7 天",
          "zh_Hans": "集中 hourly sweep(启动后 1 分首 sweep):mesh 30 天、radio/neighbour 24h、app log 24h、net_bucket 7 天",
          "en": "Centralized hourly sweep (first sweep 1 min after start): mesh 30 days, radio/neighbour 24h, app log 24h, net_bucket 7 days",
          "ja": "毎時スイープを一元化(起動 1 分後に最初の実行)。mesh 30 日、radio/neighbour 24h、アプリログ 24h、net_bucket 7 日",
          "ko": "매시간 스윕을 중앙화(시작 1분 후 첫 실행). mesh 30일, radio/neighbour 24h, 앱 로그 24h, net_bucket 7일",
          "th": "รวมการกวาดล้างรายชั่วโมง (ครั้งแรกหลังเริ่ม 1 นาที): mesh 30 วัน, radio/neighbour 24 ชม., app log 24 ชม., net_bucket 7 วัน",
          "vi": "Quét hàng giờ tập trung (lần đầu 1 phút sau khởi động): mesh 30 ngày, radio/neighbour 24h, app log 24h, net_bucket 7 ngày",
          "id": "Sweep tiap jam terpusat (pertama 1 menit setelah start): mesh 30 hari, radio/neighbour 24 jam, app log 24 jam, net_bucket 7 hari",
          "fil": "Sentrong hourly sweep (una 1 minuto pagkatapos magsimula): mesh 30 araw, radio/neighbour 24h, app log 24h, net_bucket 7 araw",
        },
      },
      {
        'key': {
          "zh_Hant": "流量記帳",
          "zh_Hans": "流量记帐",
          "en": "Traffic accounting",
          "ja": "トラフィック記帳",
          "ko": "트래픽 회계",
          "th": "การบันทึกปริมาณการใช้",
          "vi": "Hạch toán lưu lượng",
          "id": "Akuntansi lalu lintas",
          "fil": "Pagbibilang ng traffic",
        },
        'value': {
          "zh_Hant": "net_bucket 每小時記 down/saved/hits/misses;trailing window(24h/7d),可自證省流量",
          "zh_Hans": "net_bucket 每小时记 down/saved/hits/misses;trailing window(24h/7d),可自证省流量",
          "en": "net_bucket records down/saved/hits/misses hourly; trailing window (24h/7d) proves your data savings",
          "ja": "net_bucket が down/saved/hits/misses を毎時記録。trailing window(24h/7d)で通信量の節約を実証できる",
          "ko": "net_bucket이 down/saved/hits/misses를 매시간 기록. trailing window(24h/7d)로 데이터 절약을 스스로 증명",
          "th": "net_bucket บันทึก down/saved/hits/misses รายชั่วโมง; trailing window (24 ชม./7 วัน) พิสูจน์การประหยัดดาต้าได้",
          "vi": "net_bucket ghi down/saved/hits/misses mỗi giờ; cửa sổ trượt (24h/7 ngày) tự chứng minh tiết kiệm dữ liệu",
          "id": "net_bucket mencatat down/saved/hits/misses per jam; trailing window (24 jam/7 hari) membuktikan penghematan data",
          "fil": "Nagre-record ang net_bucket ng down/saved/hits/misses kada oras; trailing window (24h/7 araw) nagpapatunay ng tipid sa data",
        },
      },
    ],
    'stats': <Map<String, dynamic>>[],
  },
  {
    'id': "map_engine",
    'icon': "layers",
    'title': {
      "zh_Hant": "地圖引擎重寫:三層 tile cache 與順滑 scrub",
      "zh_Hans": "地图引擎重写:三层 tile cache 与顺滑 scrub",
      "en": "Map engine rewrite: three-tier tile cache & silky scrubbing",
      "ja": "地図エンジン刷新:3 層タイルキャッシュとなめらかなスクラブ",
      "ko": "지도 엔진 재작성: 3계층 타일 캐시와 부드러운 스크럽",
      "th": "เขียนเอนจินแผนที่ใหม่: แคชไทล์ 3 ชั้นและการสครับที่ลื่นไหล",
      "vi": "Viết lại engine bản đồ: cache tile ba tầng & lướt mượt",
      "id": "Tulis ulang engine peta: cache tile tiga tingkat & scrub mulus",
      "fil": "Muling isinulat ang map engine: three-tier tile cache & makinis na scrub",
    },
    'headline': null,
    'body': {
      "zh_Hant": "MapLibre Native 6.27.0 + ExpTech fork,vector tile、terrain-RGB、WebP raster。關鍵在於三層分工快取與雷達 scrub 的七種機制。檔案:`shared/map/*` + `features/map/*`。",
      "zh_Hans": "MapLibre Native 6.27.0 + ExpTech fork,vector tile、terrain-RGB、WebP raster。关键在于三层分工快取与雷达 scrub 的七种机制。档案:shared/map/* + features/map/*。",
      "en": "MapLibre Native 6.27.0 + ExpTech fork — vector tiles, terrain-RGB, WebP rasters. The key is the three-tier cache division and seven mechanisms behind silky radar scrubbing. Files: shared/map/* + features/map/*.",
      "ja": "MapLibre Native 6.27.0 + ExpTech フォーク。ベクタータイル、terrain-RGB、WebP ラスター。鍵は 3 層キャッシュの分担と、レーダーのなめらかなスクラブを支える 7 つの仕組み。ファイル: shared/map/* + features/map/*。",
      "ko": "MapLibre Native 6.27.0 + ExpTech 포크. 벡터 타일, terrain-RGB, WebP 래스터. 핵심은 3계층 캐시 분담과 레이더 스크럽의 7가지 메커니즘. 파일: shared/map/* + features/map/*.",
      "th": "MapLibre Native 6.27.0 + ExpTech fork — vector tile, terrain-RGB, WebP raster ระบบสำคัญคือการแบ่งแคช 3 ชั้นและกลไก 7 อย่างในการสครับเรดาร์ ไฟล์: shared/map/* + features/map/*",
      "vi": "MapLibre Native 6.27.0 + bản fork ExpTech — vector tile, terrain-RGB, raster WebP. Mấu chốt là phân chia cache ba tầng và bảy cơ chế lướt radar mượt. File: shared/map/* + features/map/*.",
      "id": "MapLibre Native 6.27.0 + fork ExpTech — vector tile, terrain-RGB, raster WebP. Kuncinya pembagian cache tiga tingkat dan tujuh mekanisme scrub radar mulus. File: shared/map/* + features/map/*.",
      "fil": "MapLibre Native 6.27.0 + ExpTech fork — vector tiles, terrain-RGB, WebP rasters. Ang susi ay ang three-tier cache at pitong mekanismo sa likod ng makinis na radar scrub. Files: shared/map/* + features/map/*.",
    },
    'stat': null,
    'statLabel': null,
    'highlights': <Map<String, String>>[],
    'details': <Map<String, dynamic>>[
      {
        'key': {
          "zh_Hant": "層 1:原生 ambient",
          "zh_Hans": "层 1:原生 ambient",
          "en": "Layer 1: native ambient",
          "ja": "層 1: ネイティブ ambient",
          "ko": "1단계: 네이티브 ambient",
          "th": "ชั้น 1: ambient ดั้งเดิม",
          "vi": "Tầng 1: ambient gốc",
          "id": "Lapisan 1: ambient native",
          "fil": "Layer 1: native ambient",
        },
        'value': {
          "zh_Hant": "最終關掉(設 0):否則與自家 SQLite 重複 ≈214 MB,且只有一份看得見流量",
          "zh_Hans": "最终关掉(设 0):否则与自家 SQLite 重复 ≈214 MB,且只有一份看得见流量",
          "en": "Disabled in the end (set to 0): otherwise it duplicated the SQLite store by ≈214 MB, with only one copy visible to accounting",
          "ja": "最終的に無効化(0 に設定)。有効だと SQLite と約 214 MB 重複し、流量会計に見えるのは片方だけになるため",
          "ko": "결국 비활성화(0으로 설정). 켜두면 SQLite와 약 214MB 중복되고, 회계에는 하나만 보임",
          "th": "ปิดในที่สุด (ตั้งเป็น 0): ไม่เช่นนั้นซ้ำกับ SQLite ประมาณ 214 MB และมีเพียงชุดเดียวที่เห็นในบัญชี流量",
          "vi": "Tắt hẳn (đặt 0): nếu không sẽ trùng với SQLite ≈214 MB, và chỉ một bản được hạch toán",
          "id": "Akhirnya dimatikan (set 0): kalau tidak, duplikat dengan SQLite ≈214 MB dan hanya satu yang terhitung",
          "fil": "Naka-disable sa huli (set to 0): kung hindi, magdadoble ito sa SQLite nang ≈214 MB, at isa lang ang nakikita ng accounting",
        },
      },
      {
        'key': {
          "zh_Hant": "層 2:權威 SQLite",
          "zh_Hans": "层 2:权威 SQLite",
          "en": "Layer 2: authoritative SQLite",
          "ja": "層 2: 権威 SQLite",
          "ko": "2단계: 권위 SQLite",
          "th": "ชั้น 2: SQLite หลัก",
          "vi": "Tầng 2: SQLite chủ đạo",
          "id": "Lapisan 2: SQLite otoritatif",
          "fil": "Layer 2: authoritative SQLite",
        },
        'value': {
          "zh_Hant": "EtagCacheStore(350 MB、LRU、URL-keyed);bridge 雙向批次,一個 IN query 取整批 tile",
          "zh_Hans": "EtagCacheStore(350 MB、LRU、URL-keyed);bridge 双向批次,一个 IN query 取整批 tile",
          "en": "EtagCacheStore (350 MB, LRU, URL-keyed); batched bridge both ways — one IN query fetches a whole tile batch",
          "ja": "EtagCacheStore(350 MB、LRU、URL キー)。ブリッジは双方向バッチ。1 つの IN クエリでタイル一式を取得",
          "ko": "EtagCacheStore(350MB, LRU, URL 키). 브리지는 양방향 배치. 하나의 IN 쿼리로 타일 묶음 전체 조회",
          "th": "EtagCacheStore (350 MB, LRU, URL-keyed); bridge แบบแบตช์ 2 ทาง — หนึ่ง IN query เรียกไทล์ทั้งชุด",
          "vi": "EtagCacheStore (350 MB, LRU, URL-keyed); bridge theo lô hai chiều — một câu IN query lấy cả lô tile",
          "id": "EtagCacheStore (350 MB, LRU, URL-keyed); bridge batch dua arah — satu query IN mengambil seluruh batch tile",
          "fil": "EtagCacheStore (350 MB, LRU, URL-keyed); batched bridge both ways — isang IN query ang kumukuha ng buong tile batch",
        },
      },
      {
        'key': {
          "zh_Hant": "層 3:記憶體 mirror",
          "zh_Hans": "层 3:记忆体 mirror",
          "en": "Layer 3: in-memory mirror",
          "ja": "層 3: メモリミラー",
          "ko": "3단계: 메모리 미러",
          "th": "ชั้น 3: มิเรอร์ในหน่วยความจำ",
          "vi": "Tầng 3: mirror trong bộ nhớ",
          "id": "Lapisan 3: mirror di memori",
          "fil": "Layer 3: in-memory mirror",
        },
        'value': {
          "zh_Hant": "MapTileCache(native in-process,48 MB);warm 把 SQLite bytes 直接注入,frame 揭露時 zero IPC/SQL/network",
          "zh_Hans": "MapTileCache(native in-process,48 MB);warm 把 SQLite bytes 直接注入,frame 揭露时 zero IPC/SQL/network",
          "en": "MapTileCache (native in-process, 48 MB); warm() injects SQLite bytes directly, so revealing a frame costs zero IPC/SQL/network",
          "ja": "MapTileCache(ネイティブ in-process、48 MB)。warm() が SQLite の bytes を直接注入し、フレーム公開時は IPC・SQL・ネットワークすべてゼロ",
          "ko": "MapTileCache(네이티브 in-process, 48MB). warm()이 SQLite bytes를 직접 주입해 프레임 공개 시 IPC/SQL/네트워크 0",
          "th": "MapTileCache (native in-process, 48 MB); warm() ฉีดไบต์จาก SQLite โดยตรง การแสดงเฟรมใช้ IPC/SQL/network เป็นศูนย์",
          "vi": "MapTileCache (native in-process, 48 MB); warm() nạp trực tiếp bytes từ SQLite, lộ khung tốn 0 IPC/SQL/network",
          "id": "MapTileCache (native in-process, 48 MB); warm() menyuntikkan bytes SQLite langsung, membuka frame nol IPC/SQL/network",
          "fil": "MapTileCache (native in-process, 48 MB); ang warm() ay direktang nag-iinject ng SQLite bytes, kaya ang pagpapakita ng frame ay zero IPC/SQL/network",
        },
      },
      {
        'key': {
          "zh_Hant": "Scrub 七機制",
          "zh_Hans": "Scrub 七机制",
          "en": "Seven scrub mechanisms",
          "ja": "スクラブの 7 つの仕組み",
          "ko": "스크럽 7가지 메커니즘",
          "th": "กลไกสครับ 7 อย่าง",
          "vi": "Bảy cơ chế scrub",
          "id": "Tujuh mekanisme scrub",
          "fil": "Pitong mekanismo ng scrub",
        },
        'value': {
          "zh_Hant": "opacity flip、0ms cross-fade、skipNulls、hide/show 併發、latest-wins pump、fling 阻尼、固定 itemExtent 清單",
          "zh_Hans": "opacity flip、0ms cross-fade、skipNulls、hide/show 并发、latest-wins pump、fling 阻尼、固定 itemExtent 清单",
          "en": "Opacity flip, 0ms cross-fade, skipNulls, concurrent hide/show, latest-wins pump, fling damping, fixed-itemExtent list",
          "ja": "opacity flip、0ms cross-fade、skipNulls、hide/show 並列、latest-wins pump、フリング減衰、固定 itemExtent リスト",
          "ko": "opacity flip, 0ms cross-fade, skipNulls, hide/show 동시, latest-wins pump, 플링 감쇠, 고정 itemExtent 목록",
          "th": "opacity flip, 0ms cross-fade, skipNulls, hide/show พร้อมกัน, latest-wins pump, หน่วง fling, รายการ itemExtent คงที่",
          "vi": "opacity flip, cross-fade 0ms, skipNulls, hide/show song song, latest-wins pump, giảm chấn fling, danh sách itemExtent cố định",
          "id": "opacity flip, cross-fade 0ms, skipNulls, hide/show konkuren, latest-wins pump, peredaman fling, daftar itemExtent tetap",
          "fil": "Opacity flip, 0ms cross-fade, skipNulls, sabay na hide/show, latest-wins pump, fling damping, fixed-itemExtent list",
        },
      },
    ],
    'stats': <Map<String, dynamic>>[],
  },
  {
    'id': "app_time",
    'icon': "query_stats",
    'title': {
      "zh_Hant": "校時與單調時鐘",
      "zh_Hans": "校时与单调时钟",
      "en": "Time sync & the monotonic clock",
      "ja": "時刻同期とモノトニッククロック",
      "ko": "시간 동기화와 모노토닉 클록",
      "th": "การซิงค์เวลาและนาฬิกาโมโนโทนิก",
      "vi": "Đồng bộ giờ & đồng hồ đơn điệu",
      "id": "Sinkronisasi waktu & jam monotonik",
      "fil": "Time sync at ang monotonic clock",
    },
    'headline': null,
    'body': {
      "zh_Hant": "真 SNTP(UDP/123,主/備)校正,錨定在 monotonic clock;所有伺服器蓋時間戳的事物都用 AppTime,永不 DateTime.now()。檔案:`core/time/*`。",
      "zh_Hans": "真 SNTP(UDP/123,主/备)校正,锚定在 monotonic clock;所有伺服器盖时间戳的事物都用 AppTime,永不 DateTime.now()。档案:core/time/*。",
      "en": "Real SNTP (UDP/123, primary/backup) synced and anchored to the monotonic clock; everything the server timestamps goes through AppTime, never DateTime.now(). Files: core/time/*.",
      "ja": "本物の SNTP(UDP/123、主/副)で同期し、モノトニッククロックに固定。サーバーがタイムスタンプを付けるものはすべて AppTime 経由で、DateTime.now() は使わない。ファイル: core/time/*。",
      "ko": "진짜 SNTP(UDP/123, 주/백업)로 동기화하고 모노토닉 클록에 앵커. 서버가 타임스탬프를 찍는 모든 것은 AppTime 사용, DateTime.now()는 금지. 파일: core/time/*.",
      "th": "ใช้ SNTP จริง (UDP/123, หลัก/สำรอง) ซิงค์และยึดกับนาฬิกาโมโนโทนิก ทุกอย่างที่เซิร์ฟเวอร์ประทับเวลาใช้ AppTime ไม่ใช้ DateTime.now() ไฟล์: core/time/*",
      "vi": "SNTP thật (UDP/123, chính/dự phòng) đồng bộ và neo vào đồng hồ đơn điệu; mọi thứ máy chủ đóng dấu thời gian đều qua AppTime, không bao giờ DateTime.now(). File: core/time/*.",
      "id": "SNTP asli (UDP/123, utama/cadangan) sinkron dan berjangkar pada jam monotonik; semua yang distempel waktu server lewat AppTime, tidak pernah DateTime.now(). File: core/time/*.",
      "fil": "Tunay na SNTP (UDP/123, primary/backup) na naka-angkla sa monotonic clock; lahat ng may timestamp ng server ay dumadaan sa AppTime, hindi kailanman DateTime.now(). Files: core/time/*.",
    },
    'stat': null,
    'statLabel': null,
    'highlights': <Map<String, String>>[],
    'details': <Map<String, dynamic>>[
      {
        'key': {
          "zh_Hant": "Legacy 對比",
          "zh_Hans": "Legacy 对比",
          "en": "vs. Legacy",
          "ja": "旧版との比較",
          "ko": "구버전과 비교",
          "th": "เทียบกับเดิม",
          "vi": "So với bản cũ",
          "id": "vs Legacy",
          "fil": "vs Legacy",
        },
        'value': {
          "zh_Hant": "Legacy:自家 HTTP 端點每分鐘校正,currentTime = now + offset;新版:標準協定 + monotonic 錨定,改鐘不移動時間",
          "zh_Hans": "Legacy:自家 HTTP 端点每分钟校正,currentTime = now + offset;新版:标准协定 + monotonic 锚定,改钟不移动时间",
          "en": "Legacy: custom HTTP endpoint corrected every minute (now + offset); new: standard protocol + monotonic anchoring, clock edits don't move time",
          "ja": "旧版: 独自 HTTP エンドポイントで毎分補正 (now + offset)。新版: 標準プロトコル + モノトニック固定。時計操作は時間を動かさない",
          "ko": "구버전: 자체 HTTP 엔드포인트로 매분 보정(now + offset). 신버전: 표준 프로토콜 + 모노토닉 앵커. 시계 조작이 시간을 움직이지 않음",
          "th": "เดิม: endpoint HTTP เอง ปรับทุกนาที (now + offset); ใหม่: โปรโตคอลมาตรฐาน + ผูกกับ monotonic การแก้นาฬิกาไม่ขยับเวลา",
          "vi": "Cũ: endpoint HTTP tự chế chỉnh mỗi phút (now + offset); mới: giao thức chuẩn + neo monotonic, sửa đồng hồ không làm lệch thời gian",
          "id": "Legacy: endpoint HTTP sendiri dikoreksi setiap menit (now + offset); baru: protokol standar + jangkar monotonik, ubah jam tak menggeser waktu",
          "fil": "Legacy: sariling HTTP endpoint, minuto-minutong inaayos (now + offset); bago: standard na protocol + monotonic anchoring, hindi gumagalaw ang oras kahit baguhin ang clock",
        },
      },
    ],
    'stats': <Map<String, dynamic>>[],
  },
  {
    'id': "error_model",
    'icon': "rule",
    'title': {
      "zh_Hant": "錯誤模型:Result<T> 取代散落 throw",
      "zh_Hans": "错误模型:Result<T> 取代散落 throw",
      "en": "Error model: Result<T> replaces scattered throws",
      "ja": "エラーモデル: Result<T> が散らばった throw を置き換え",
      "ko": "오류 모델: Result<T>가 흩어진 throw를 대체",
      "th": "โมเดลข้อผิดพลาด: Result<T> แทนที่ throw ที่กระจาย",
      "vi": "Mô hình lỗi: Result<T> thay thế throw lộn xộn",
      "id": "Model error: Result<T> menggantikan throw tersebar",
      "fil": "Error model: Result<T> ang pumalit sa nagkalat na throw",
    },
    'headline': null,
    'body': {
      "zh_Hant": "資料層方法回 Result 而非 throw:「被吞掉的 exception 絕不能變成靜默的 all-clear」——對防災 app 這是最糟的失敗模式。檔案:`core/error/*`。",
      "zh_Hans": "资料层方法回 Result 而非 throw:「被吞掉的 exception 绝不能被变成静默的 all-clear」——对防灾 app 这是最糟的失败模式。档案:core/error/*。",
      "en": "Data-layer methods return Result instead of throwing: 'a swallowed exception must never become a silent all-clear' — the worst failure mode for a disaster app. Files: core/error/*.",
      "ja": "データ層のメソッドは throw ではなく Result を返す。「握りつぶされた例外が静かな全クリアになってはならない」—防災アプリにとって最悪の失敗モード。ファイル: core/error/*。",
      "ko": "데이터 계층 메서드는 throw 대신 Result 반환: \"삼켜진 예외가 조용한 올클리어가 되어선 안 된다\" — 방재 앱에 최악의 실패 모드. 파일: core/error/*.",
      "th": "เมธอดเลเยอร์ข้อมูลคืน Result แทนการ throw: \"exception ที่ถูกกลืนต้องไม่กลายเป็นการเคลียร์แบบเงียบ\" — โหมดความล้มเหลวที่แย่ที่สุดสำหรับแอปภัยพิบัติ ไฟล์: core/error/*",
      "vi": "Method tầng dữ liệu trả Result thay vì throw: 'exception bị nuốt không bao giờ được trở thành tất-cả-rõ-ràng thầm lặng' — chế độ lỗi tệ nhất cho app thảm hoạ. File: core/error/*.",
      "id": "Metode lapisan data mengembalikan Result, bukan throw: 'exception yang ditelan tidak boleh menjadi all-clear senyap' — mode gagal terburuk untuk aplikasi bencana. File: core/error/*.",
      "fil": "Ang data-layer methods ay nagbabalik ng Result imbes na mag-throw: 'ang nalamon na exception ay hindi dapat maging tahimik na all-clear' — pinakamasamang failure mode para sa disaster app. Files: core/error/*.",
    },
    'stat': null,
    'statLabel': null,
    'highlights': <Map<String, String>>[],
    'details': <Map<String, dynamic>>[
      {
        'key': {
          "zh_Hant": "Failure 階層",
          "zh_Hans": "Failure 阶层",
          "en": "Failure hierarchy",
          "ja": "Failure 階層",
          "ko": "Failure 계층",
          "th": "ลำดับชั้น Failure",
          "vi": "Hệ tầng Failure",
          "id": "Hierarki Failure",
          "fil": "Failure hierarchy",
        },
        'value': {
          "zh_Hant": "Network / Timeout / Decode / NoData(空 list ≠ 錯誤)/ Unexpected / MeshConflict",
          "zh_Hans": "Network / Timeout / Decode / NoData(空 list ≠ 错误)/ Unexpected / MeshConflict",
          "en": "Network / Timeout / Decode / NoData (empty list ≠ error) / Unexpected / MeshConflict",
          "ja": "Network / Timeout / Decode / NoData(空リスト ≠ エラー)/ Unexpected / MeshConflict",
          "ko": "Network / Timeout / Decode / NoData(빈 목록 ≠ 오류) / Unexpected / MeshConflict",
          "th": "Network / Timeout / Decode / NoData (รายการว่าง ≠ ข้อผิดพลาด) / Unexpected / MeshConflict",
          "vi": "Network / Timeout / Decode / NoData (danh sách trống ≠ lỗi) / Unexpected / MeshConflict",
          "id": "Network / Timeout / Decode / NoData (list kosong ≠ error) / Unexpected / MeshConflict",
          "fil": "Network / Timeout / Decode / NoData (walang laman na list ≠ error) / Unexpected / MeshConflict",
        },
      },
      {
        'key': {
          "zh_Hant": "Timeout 獨立化",
          "zh_Hans": "Timeout 独立化",
          "en": "Timeout is its own type",
          "ja": "Timeout の独立",
          "ko": "Timeout 독립 타입",
          "th": "Timeout เป็นประเภทของตัวเอง",
          "vi": "Timeout là kiểu riêng",
          "id": "Timeout berdiri sendiri",
          "fil": "Independent ang Timeout",
        },
        'value': {
          "zh_Hant": "獨立出來,讓 realtime UI 顯示 STALE(而非泛用錯誤)而不是卡住",
          "zh_Hans": "独立出来,让 realtime UI 显示 STALE(而非泛用错误)而不是卡住",
          "en": "Separated so the realtime UI shows STALE (not a generic error) instead of hanging",
          "ja": "独立させ、リアルタイム UI が汎用エラーではなく STALE を表示できるように",
          "ko": "분리하여 실시간 UI가 일반 오류가 아닌 STALE을 표시하게",
          "th": "แยกออกมาเพื่อให้ UI เรียลไทม์แสดง STALE (ไม่ใช่ข้อผิดพลาดทั่วไป) แทนการค้าง",
          "vi": "Tách riêng để UI realtime hiển thị STALE (không phải lỗi chung) thay vì treo",
          "id": "Dipisah agar UI realtime menampilkan STALE (bukan error umum) alih-alih menggantung",
          "fil": "Inihiwalay para ang realtime UI ay magpakita ng STALE (hindi generic error) imbes na mag-hang",
        },
      },
      {
        'key': {
          "zh_Hant": "guardResult",
          "zh_Hans": "guardResult",
          "en": "guardResult",
          "ja": "guardResult",
          "ko": "guardResult",
          "th": "guardResult",
          "vi": "guardResult",
          "id": "guardResult",
          "fil": "guardResult",
        },
        'value': {
          "zh_Hant": "DB 層唯一把 throw→Result 的地方;每個 repository 方法一行,沒人會忘了 try",
          "zh_Hans": "DB 层唯一把 throw→Result 的地方;每个 repository 方法一行,没人会忘了 try",
          "en": "The only place DB-layer turns throw→Result; one line per repository method, so no one forgets the try",
          "ja": "DB 層で throw→Result に変換する唯一の場所。リポジトリメソッドあたり 1 行なので、try を忘れない",
          "ko": "DB 계층에서 throw→Result로 바꾸는 유일한 곳. 저장소 메서드당 한 줄이라 try를 잊지 않음",
          "th": "จุดเดียวที่เลเยอร์ DB เปลี่ยน throw→Result; หนึ่งบรรทัดต่อ method repository ไม่มีทางลืม try",
          "vi": "Nơi duy nhất tầng DB chuyển throw→Result; một dòng cho mỗi method repository, không ai quên try",
          "id": "Satu-satunya tempat lapisan DB mengubah throw→Result; satu baris per method repository, tidak ada yang lupa try",
          "fil": "Ang tanging lugar na ginagawang throw→Result ng DB-layer; isang linya bawat repository method, walang nakakalimot sa try",
        },
      },
    ],
    'stats': <Map<String, dynamic>>[],
  },
  {
    'id': "logging",
    'icon': "receipt_long",
    'title': {
      "zh_Hant": "持久化日誌:crash 前那一支可回放",
      "zh_Hans": "持久化日志:crash 前那一支可回放",
      "en": "Persistent log: the last 24h before a crash can be replayed",
      "ja": "永続ログ:クラッシュ前 24 時間を再生できる",
      "ko": "영구 로그: 크래시 24시간 전을 재생 가능",
      "th": "ล็อกถาวร: ย้อนดู 24 ชั่วโมงก่อน crash ได้",
      "vi": "Nhật ký bền vững: 24h trước crash có thể xem lại",
      "id": "Log persisten: 24 jam sebelum crash bisa diputar ulang",
      "fil": "Persistent log: maaaring i-replay ang 24h bago mag-crash",
    },
    'headline': null,
    'body': {
      "zh_Hant": "Log 常駐 SQLite(24h 保留)。重複錯誤抑制:同 signature 5s 窗內重複超過 8 次開始 drop。App 內「日誌」頁可回放崩潰前最後一支。檔案:`core/logging/*`。",
      "zh_Hans": "Log 常驻 SQLite(24h 保留)。重复错误抑制:同 signature 5s 窗内重复超过 8 次开始 drop。App 内「日志」页可回放崩溃前最后一支。档案:core/logging/*。",
      "en": "Logs persist in SQLite (24h retention). Repeat-error suppression: more than 8 of the same signature in a 5s window starts dropping. The in-app Log page replays the final moments before a crash. Files: core/logging/*.",
      "ja": "ログは SQLite に常駐(24 時間保持)。重複エラー抑制:同一シグネチャが 5 秒窓で 8 回超えると削り始める。アプリ内「ログ」ページでクラッシュ直前を再生できる。ファイル: core/logging/*。",
      "ko": "로그는 SQLite에 상주(24시간 보존). 반복 오류 억제: 같은 시그니처가 5초 창에서 8회 넘으면 드랍 시작. 앱 내 '로그' 페이지에서 크래시 직전을 재생 가능. 파일: core/logging/*.",
      "th": "ล็อกอยู่ใน SQLite (เก็บ 24 ชม.) ลดการซ้ำของข้อผิดพลาด: ซ้ำกันเกิน 8 ครั้งในหน้าต่าง 5 วินาทีจะเริ่มตัดทิ้ง หน้า 'Log' ในแอปสามารถย้อนดูช่วงก่อน crash ได้ ไฟล์: core/logging/*",
      "vi": "Log thường trú trong SQLite (giữ 24h). Chèn lặp lỗi: hơn 8 lần cùng signature trong cửa sổ 5s bắt đầu loại bỏ. Trang 'Nhật ký' trong app xem lại khoảnh khắc cuối trước crash. File: core/logging/*.",
      "id": "Log menetap di SQLite (retensi 24 jam). Penekanan error berulang: lebih dari 8 kali signature sama dalam jendela 5 detik mulai dibuang. Halaman Log di app memutar ulang momen terakhir sebelum crash. File: core/logging/*.",
      "fil": "Nananatili ang log sa SQLite (24h retention). Repeat-error suppression: higit sa 8 na parehong signature sa 5s window ay magsisimulang i-drop. Ang in-app Log page ay nag-re-replay ng mga huling sandali bago mag-crash. Files: core/logging/*.",
    },
    'stat': null,
    'statLabel': null,
    'highlights': <Map<String, String>>[],
    'details': <Map<String, dynamic>>[
      {
        'key': {
          "zh_Hant": "Legacy 對比",
          "zh_Hans": "Legacy 对比",
          "en": "vs. Legacy",
          "ja": "旧版との比較",
          "ko": "구버전과 비교",
          "th": "เทียบกับเดิม",
          "vi": "So với bản cũ",
          "id": "vs Legacy",
          "fil": "vs Legacy",
        },
        'value': {
          "zh_Hant":
              "Legacy: talker_flutter 純記憶體,重開機就查不到昨天為何崩潰;新版:SQLite 24h 可回放",
          "zh_Hans":
              "Legacy: talker_flutter 纯记忆体,重开机就查不到昨天为何崩溃;新版:SQLite 24h 可回放",
          "en": "Legacy: talker_flutter in memory — reboot loses the reason behind yesterday's crash; new: SQLite 24h, replayable",
          "ja": "旧版: talker_flutter はメモリのみ、再起動で昨日のクラッシュ理由は消える。新版: SQLite 24 時間再生可能",
          "ko": "구버전: talker_flutter 메모리 전용, 재부팅되면 어제 크래시 이유 조회 불가. 신버전: SQLite 24시간 재생 가능",
          "th": "เดิม: talker_flutter หน่วยความจำล้วน รีสตาร์ทแล้วหาสาเหตุ crash เมื่อวานไม่ได้; ใหม่: SQLite 24 ชม. ดูย้อนหลังได้",
          "vi": "Cũ: talker_flutter chỉ trong bộ nhớ, khởi động lại mất lý do crash hôm qua; mới: SQLite 24h, xem lại được",
          "id": "Legacy: talker_flutter murni memori, restart hilang sebab crash kemarin; baru: SQLite 24 jam, bisa diputar ulang",
          "fil": "Legacy: talker_flutter memory lang, mawawala ang dahilan ng crash kahapon pag-restart; bago: SQLite 24h, replayable",
        },
      },
    ],
    'stats': <Map<String, dynamic>>[],
  },
  {
    'id': "perf_numbers",
    'icon': "straighten",
    'title': {
      "zh_Hant": "能量化的數字",
      "zh_Hans": "能量化的数字",
      "en": "The measurable numbers",
      "ja": "定量化できる数字",
      "ko": "계량 가능한 숫자",
      "th": "ตัวเลขที่วัดได้",
      "vi": "Những con số đo lường được",
      "id": "Angka yang terukur",
      "fil": "Ang mga nasusukat na numero",
    },
    'headline': null,
    'body': {
      "zh_Hant": "所有數字都有出處。repo 沒有全域 benchmark,所以只列測得到的。Source:`REWRITE-vs-LEGACY.md`。",
      "zh_Hans":
          "所有数字都有出处。repo 没有全域 benchmark,所以只列测得到的。Source:REWRITE-vs-LEGACY.md。",
      "en": "Every number has a source. The repo has no global benchmark, so these are the ones actually measured. Source: REWRITE-vs-LEGACY.md.",
      "ja": "すべての数字に出典があります。リポジトリにグローバルなベンチマークはないため、実際に計測できたものだけを載せています。出典: REWRITE-vs-LEGACY.md。",
      "ko": "모든 숫자에 출처가 있습니다. 저장소에 전역 벤치마크가 없어 실제 측정된 것만 실었습니다. 출처: REWRITE-vs-LEGACY.md.",
      "th": "ทุกตัวเลขมีที่มา ไม่มี benchmark แบบครอบคลุมทั้ง repo จึงแสดงเฉพาะที่วัดได้จริง ที่มา: REWRITE-vs-LEGACY.md",
      "vi": "Mọi con số đều có nguồn. Repo không có benchmark toàn cục, nên chỉ liệt kê thứ đo được. Nguồn: REWRITE-vs-LEGACY.md.",
      "id": "Setiap angka punya sumber. Repo tak punya benchmark global, jadi hanya yang benar-benar terukur yang dicantumkan. Sumber: REWRITE-vs-LEGACY.md.",
      "fil": "Ang bawat numero ay may pinagmulan. Walang global benchmark ang repo, kaya ito lang ang talagang nasukat. Source: REWRITE-vs-LEGACY.md.",
    },
    'stat': null,
    'statLabel': null,
    'highlights': <Map<String, String>>[],
    'details': <Map<String, dynamic>>[],
    'stats': <Map<String, dynamic>>[
      {
        'value': {
          "zh_Hant": "−72%",
          "zh_Hans": "−72%",
          "en": "−72%",
          "ja": "−72%",
          "ko": "−72%",
          "th": "−72%",
          "vi": "−72%",
          "id": "−72%",
          "fil": "−72%",
        },
        'label': {
          "zh_Hant": "鄉鎮邊界單一資產的安裝檔縮減",
          "zh_Hans": "乡镇边界单一资产的安装档缩减",
          "en": "install-size cut for the town-boundary asset alone",
          "ja": "町境界アセット単体のインストール縮小",
          "ko": "읍면 경계 단일 에셋의 설치 축소",
          "th": "การลดขนาดแอปสำหรับ asset ขอบเขตเมืองเพียงอย่างเดียว",
          "vi": "giảm kích thước cài đặt riêng asset ranh giới",
          "id": "pemangkasan ukuran instal untuk aset batas kota saja",
          "fil": "bawas sa laki ng install para sa town-boundary asset lamang",
        },
      },
      {
        'value': {
          "zh_Hant": "1–2 秒",
          "zh_Hans": "1–2 秒",
          "en": "1–2 s",
          "ja": "1〜2 秒",
          "ko": "1~2초",
          "th": "1–2 วิ",
          "vi": "1–2 s",
          "id": "1–2 dtk",
          "fil": "1–2 s",
        },
        'label': {
          "zh_Hant": "Android 部分裝置的冷啟動省時(再 +500ms)",
          "zh_Hans": "Android 部分装置的冷启动省时(再 +500ms)",
          "en": "cold-start saving on some Android devices (+500 ms more)",
          "ja": "一部 Android 端末のコールドスタート短縮(さらに +500 ms)",
          "ko": "일부 Android 기기의 콜드 스타트 단축(+500ms 추가)",
          "th": "ประหยัดเวลาตอนเริ่มบน Android บางรุ่น (บวกอีก 500ms)",
          "vi": "khởi động lạnh nhanh hơn trên một số Android (+500 ms nữa)",
          "id": "penghematan cold start pada sebagian Android (+500ms lagi)",
          "fil": "tipid sa cold start sa ilang Android (+500ms pa)",
        },
      },
      {
        'value': {
          "zh_Hant": "350 MB",
          "zh_Hans": "350 MB",
          "en": "350 MB",
          "ja": "350 MB",
          "ko": "350MB",
          "th": "350 MB",
          "vi": "350 MB",
          "id": "350 MB",
          "fil": "350 MB",
        },
        'label': {
          "zh_Hant": "ETag 快取的 LRU byte 預算",
          "zh_Hans": "ETag 快取的 LRU byte 预算",
          "en": "ETag cache's LRU byte budget",
          "ja": "ETag キャッシュの LRU バイト予算",
          "ko": "ETag 캐시의 LRU 바이트 예산",
          "th": "งบประมาณไบต์ LRU ของแคช ETag",
          "vi": "ngân sách byte LRU của cache ETag",
          "id": "anggaran byte LRU cache ETag",
          "fil": "LRU byte budget ng ETag cache",
        },
      },
      {
        'value': {
          "zh_Hant": "1–3",
          "zh_Hans": "1–3",
          "en": "1–3",
          "ja": "1〜3",
          "ko": "1~3",
          "th": "1–3",
          "vi": "1–3",
          "id": "1–3",
          "fil": "1–3",
        },
        'label': {
          "zh_Hant": "GEO 查詢實際測試的多邊形數(舊:367)",
          "zh_Hans": "GEO 查询实际测试的多边形数(旧:367)",
          "en": "polygons actually tested per GEO query (old: 367)",
          "ja": "GEO クエリの実際にテストされるポリゴン数(旧: 367)",
          "ko": "GEO 쿼리당 실제 테스트 폴리곤 수(이전: 367)",
          "th": "จำนวนรูปหลายเหลี่ยมที่ทดสอบจริงต่อการค้นหา GEO (เดิม: 367)",
          "vi": "số đa giác thực sự được kiểm tra mỗi truy vấn GEO (cũ: 367)",
          "id": "poligon yang benar-benar diuji per kueri GEO (lama: 367)",
          "fil": "polygon na talagang tinitingnan bawat GEO query (dati: 367)",
        },
      },
    ],
  },
  {
    'id': "crash_fixes",
    'icon': "bug_report",
    'title': {
      "zh_Hant": "直接修掉的 crash",
      "zh_Hans": "直接修掉的 crash",
      "en": "Crashes fixed along the way",
      "ja": "直したクラッシュ",
      "ko": "고친 크래시",
      "th": "crash ที่แก้แล้ว",
      "vi": "Các crash đã sửa",
      "id": "Crash yang diperbaiki",
      "fil": "Mga crash na naayos",
    },
    'headline': null,
    'body': {
      "zh_Hant": "重寫過程中也修掉幾個潛在 crash:相機框景在 Dart 端算(原生對 degenerate box 會丟未捕捉 exception 直接 SIGABRT)、MapLibre fork 加 Android gzip 修正、閃電 PNG 明確 dispose(修掉每 register 一次洩兩個 native handle)。",
      "zh_Hans": "重写过程中也修掉几个潜在 crash:相机框景在 Dart 端算(原生对 degenerate box 会丢未捕捉 exception 直接 SIGABRT)、MapLibre fork 加 Android gzip 修正、闪电 PNG 明确 dispose(修掉每 register 一次泄两个 native handle)。",
      "en": "The rewrite also fixed lurking crashes: the camera frame is computed in Dart (native throws an uncaught exception on degenerate boxes → SIGABRT), the MapLibre fork adds an Android gzip fix, and lightning PNGs are explicitly disposed (two native handle leaks per register).",
      "ja": "リライトで潜在クラッシュも修正。カメラフレームは Dart 側で計算(ネイティブは退化ボックスで未捕捉例外→SIGABRT)。MapLibre フォークで Android の gzip 問題を修正。雷 PNG を明示的 dispose(register ごとにネイティブハンドル 2 つのリークを修正)。",
      "ko": "재작성 과정에서 잠재 크래시도 수정됐습니다. 카메라 프레임을 Dart에서 계산(네이티브는 degenerate box에서 미처리 예외 → SIGABRT). MapLibre 포크로 Android gzip 수정. 번개 PNG 명시적 dispose(register마다 네이티브 핸들 2개 누수 수정).",
      "th": "การเขียนใหม่ยังแก้ crash ที่ซ่อนอยู่ด้วย: คำนวณเฟรมกล้องใน Dart (เนทีฟยิง exception ที่ไม่ catch ใน degenerate box → SIGABRT), MapLibre fork เพิ่มการแก้ gzip Android, และ dispose PNG สายฟ้าอย่างชัดเจน (แก้หน่วยความจำรั่ว 2 handle ต่อการ register)",
      "vi": "Việc viết lại cũng sửa các crash tiềm ẩn: khung camera tính trong Dart (native ném exception chưa bắt trên box suy biến → SIGABRT), fork MapLibre thêm bản vá gzip Android, PNG sét được dispose tường minh (sửa rò rỉ 2 native handle mỗi lần register).",
      "id": "Penulisan ulang juga memperbaiki crash tersembunyi: bingkai kamera dihitung di Dart (native melempar exception tak tertangkap pada kotak degenerate → SIGABRT), fork MapLibre menambah perbaikan gzip Android, PNG petir di-dispose eksplisit (memperbaiki kebocoran 2 native handle per register).",
      "fil": "Ang rewrite ay nag-ayos din ng mga nakatagong crash: ang camera frame ay kinukwenta sa Dart (nag-throw ng uncaught exception ang native sa degenerate box → SIGABRT), ang MapLibre fork ay may Android gzip fix, at ang lightning PNG ay eksplisit na dine-dispose (dalawang native handle leak bawat register).",
    },
    'stat': null,
    'statLabel': null,
    'highlights': <Map<String, String>>[],
    'details': <Map<String, dynamic>>[],
    'stats': <Map<String, dynamic>>[],
  },
];
